"""Public API for the context-compaction pipeline."""

from lamtools_core.context_compaction_budget import (
    CONTEXT_COMPACTION_NAMESPACE,
    DEFAULT_RETAINED_STEPS,
    MAX_RETAINED_STEPS,
    MAX_RETAINED_USER_MESSAGES,
    SummaryTokenBudget,
    TokenBudget,
    TokenMeasurement,
    load_retained_steps,
    measure_for_compaction_trigger,
    resolve_compaction_budget,
    resolve_retained_steps,
)
from .models import (
    COMPACTION_PREFIX,
    COMPACTION_PROMPT,
    CompactionBudgetExceeded,
    CompactionDeltaSink,
    CompactionEventSink,
    CompactionFitInput,
    CompactionFitResult,
    CompactionOptions,
    CompactionPlan,
    CompactionSummary,
    CompactionTokenEstimator,
    ContextCompactionError,
    ContextCompactionRequest,
    ContextCompactionResult,
)
from .formatting import (
    RECENT_USER_MESSAGES_HEADING,
    RECENT_USER_MESSAGES_METADATA_KEY,
    NON_TEXT_USER_MESSAGE_PLACEHOLDER,
    format_messages_for_compaction,
    append_recent_user_messages,
    extract_recent_user_messages,
    parse_compaction_summary,
    recent_user_message_text,
    strip_recent_user_messages,
    user_message_text,
    with_compaction_prefix,
)
from .fallback import (
    compress_structured_compaction_summary,
    fallback_structured_compaction_summary,
)
from .planner import (
    CompactionPlanner,
    compaction_segment_input_limit,
    select_context_compaction_layout,
)
from .fitter import CompactionFitter, MAX_FIT_ATTEMPTS, truncate_text_to_tokens
from .summarizer import summarize_context_messages
from .controller import (
    CompactionExecution,
    ContextCompactionController,
    ContextCompactor,
    compact_context,
)
from .usage_anchor import (
    RequestPrefix,
    USAGE_ANCHOR_METADATA_KEY,
    USAGE_ANCHOR_SOURCE,
    build_usage_anchor,
    describe_request,
    effective_prompt_tokens,
    measure_with_usage_anchor,
    message_prefix_digest,
    request_overhead_digest,
)


__all__ = [
    "COMPACTION_PREFIX",
    "COMPACTION_PROMPT",
    "RECENT_USER_MESSAGES_HEADING",
    "RECENT_USER_MESSAGES_METADATA_KEY",
    "NON_TEXT_USER_MESSAGE_PLACEHOLDER",
    "CONTEXT_COMPACTION_NAMESPACE",
    "DEFAULT_RETAINED_STEPS",
    "RequestPrefix",
    "USAGE_ANCHOR_METADATA_KEY",
    "USAGE_ANCHOR_SOURCE",
    "build_usage_anchor",
    "describe_request",
    "effective_prompt_tokens",
    "measure_with_usage_anchor",
    "message_prefix_digest",
    "request_overhead_digest",
    "CompactionBudgetExceeded",
    "CompactionExecution",
    "CompactionFitInput",
    "CompactionFitResult",
    "CompactionFitter",
    "CompactionOptions",
    "CompactionPlan",
    "CompactionPlanner",
    "CompactionSummary",
    "ContextCompactionError",
    "ContextCompactionController",
    "ContextCompactor",
    "ContextCompactionRequest",
    "ContextCompactionResult",
    "MAX_FIT_ATTEMPTS",
    "MAX_RETAINED_STEPS",
    "MAX_RETAINED_USER_MESSAGES",
    "compact_context",
    "compress_structured_compaction_summary",
    "compaction_segment_input_limit",
    "fallback_structured_compaction_summary",
    "format_messages_for_compaction",
    "append_recent_user_messages",
    "extract_recent_user_messages",
    "load_retained_steps",
    "parse_compaction_summary",
    "recent_user_message_text",
    "resolve_compaction_budget",
    "resolve_retained_steps",
    "select_context_compaction_layout",
    "strip_recent_user_messages",
    "summarize_context_messages",
    "truncate_text_to_tokens",
    "user_message_text",
    "with_compaction_prefix",
]
