"""Local, model-free summary fallback helpers."""

from __future__ import annotations

import json

from lamtools_core.llm import ChatMessage
from lamtools_core.tokens import estimate_text_tokens

from .formatting import (
    line_is_in_numbered_sections,
    numbered_section_number,
    truncate_text_to_tokens,
)
from .models import COMPACTION_PREFIX, CompactionSummary


def fallback_structured_compaction_summary(
    messages: list[ChatMessage],
    *,
    existing_summary: str = "",
) -> str:
    snippets: list[str] = []
    user_snippets: list[str] = []
    if existing_summary.strip():
        snippets.append(f"- existing summary: {existing_summary.strip()[:800]}")
    for message in messages:
        content = message.content
        if not isinstance(content, str):
            content = json.dumps(content, ensure_ascii=False)
        text = " ".join(content.split())
        if not text:
            continue
        role = "internal" if message.metadata.get("internal") else message.role
        snippets.append(f"- {role}: {text[:500]}")
        if message.role == "user" and not message.metadata.get("internal"):
            user_snippets.append(f"- {text[:500]}")
    body = "\n".join(snippets) if snippets else "- No compactable details captured."
    user_body = "\n".join(user_snippets) if user_snippets else "- No prior user instructions in compacted span."
    return CompactionSummary(
        goals=(
            "- Continue the active user task using the latest uncompressed user message.\n"
            "- Completion criteria were not independently reconstructed by the local fallback."
        ),
        active_user_instructions=user_body,
        external_action_authorization=(
            "- Preserve explicit approval and prohibition language from the active user instructions.\n"
            "- Do not infer permission for commits, pushes, pull requests, deployments, messages, purchases, or destructive actions."
        ),
        confirmed_facts_and_decisions=(
            "- Only details present in the compacted messages are confirmed; do not promote guesses to facts."
        ),
        current_execution_state=body,
        verification_evidence=(
            "- Preserve exact paths, identifiers, commands, errors, and test results from the execution-state snippets above."
        ),
        open_issues_risks_and_hypotheses=(
            "- This summary was generated by local fallback; inferred causes remain unverified."
        ),
        rejected_or_superseded_directions=(
            "- Retain only rejected or superseded directions explicitly present in the compacted messages."
        ),
        next_actions="- Continue from the latest user request and verify with tests where applicable.",
    ).render()


def compress_structured_compaction_summary(text: str, max_tokens: int) -> str:
    if max_tokens <= 0:
        return ""

    raw_lines = [line.rstrip() for line in text.splitlines()]
    if raw_lines and raw_lines[0].strip() == COMPACTION_PREFIX:
        raw_lines = raw_lines[1:]

    sections: list[tuple[str, list[str]]] = []
    current_title = ""
    current_lines: list[str] = []
    for line in raw_lines:
        stripped = line.strip()
        if stripped and len(stripped) > 3 and stripped[0].isdigit() and ". " in stripped[:4]:
            if current_title:
                sections.append((current_title, current_lines))
            current_title = stripped
            current_lines = []
            continue
        if current_title:
            current_lines.append(line)
    if current_title:
        sections.append((current_title, current_lines))

    if not sections:
        return truncate_text_to_tokens(text, max_tokens)

    compacted_lines = [COMPACTION_PREFIX]
    for title, lines in sections:
        compacted_lines.extend(["", title])
        kept = 0
        omitted = False
        is_protected_section = title.startswith(("2. ", "3. "))
        for line in lines:
            stripped = " ".join(line.strip().split())
            if not stripped:
                continue
            if len(stripped) > 260:
                if is_protected_section:
                    stripped = stripped[:260]
                else:
                    omitted = True
                    continue
            compacted_lines.append(stripped)
            kept += 1
            if kept >= 3 and not is_protected_section:
                break
        if omitted:
            compacted_lines.append("- Details omitted because this section exceeded the compaction budget.")
        if kept == 0 and not omitted:
            compacted_lines.append("- No durable details retained.")

    candidate = "\n".join(compacted_lines).strip()
    if estimate_text_tokens(candidate) <= max_tokens:
        return candidate

    lines = candidate.splitlines()
    while lines and estimate_text_tokens("\n".join(lines)) > max_tokens:
        def can_remove(index: int, *, headings: bool = False) -> bool:
            stripped = lines[index].strip()
            if stripped == COMPACTION_PREFIX or line_is_in_numbered_sections(lines, index, {2, 3}):
                return False
            return headings or numbered_section_number(stripped) is None

        remove_index = next(
            (
                index
                for index in range(len(lines) - 1, -1, -1)
                if lines[index].startswith("- ")
                and can_remove(index)
            ),
            next(
                (
                    index
                    for index in range(len(lines) - 1, -1, -1)
                    if can_remove(index)
                ),
                next(
                    (
                        index
                        for index in range(len(lines) - 1, -1, -1)
                        if lines[index].startswith("- ")
                        and can_remove(index, headings=True)
                    ),
                    next(
                        (
                            index
                            for index in range(len(lines) - 1, -1, -1)
                            if can_remove(index, headings=True)
                        ),
                        -1,
                    ),
                ),
            ),
        )
        if remove_index < 0:
            break
        lines.pop(remove_index)
    return "\n".join(lines).strip()


__all__ = [
    "compress_structured_compaction_summary",
    "fallback_structured_compaction_summary",
]
