from .engine import HookEngine
from .context import PluginContext
from .hook_config import HookRegistry, default_project_hooks_path, default_user_hooks_path
from .models import (
    HookDecision,
    HookDefinition,
    HookEvent,
    HookHandler,
    PluginManifest,
    PluginCLIArgument,
    PluginCLICommand,
    PluginCLIContribution,
    PluginComposerCommand,
    PluginResource,
    PluginSidebarWidget,
    PluginUIContribution,
    PluginUIMode,
    PluginUIView,
    PluginWidgetAction,
    # canonical hook event names
    HOOK_EVENT_PRE_TOOL_USE,
    HOOK_EVENT_POST_TOOL_USE,
    HOOK_EVENT_POST_TOOL_USE_FAILURE,
    HOOK_EVENT_SESSION_START,
    HOOK_EVENT_SESSION_STOP,
    HOOK_EVENT_USER_PROMPT_SUBMIT,
    HOOK_EVENT_PERMISSION_REQUEST,
)
from .operations import build_plugin_operation_catalog
from .registry import (
    PluginRegistry,
    PluginStateStore,
    default_project_plugin_root,
    default_user_plugin_root,
)
from .trust import HookTrustStore
from .lifecycle import (
    PluginRuntimeManager,
    PluginRuntimeHandle,
    attach_plugin_runtime,
    load_enabled_plugin_backends,
    load_plugin_backend,
    start_plugin_backend,
    stop_plugin_backend,
    shutdown_plugin_backends,
)

__all__ = [
    "HookDecision",
    "HookDefinition",
    "HookEngine",
    "HookEvent",
    "HookHandler",
    "HookRegistry",
    "HookTrustStore",
    "PluginManifest",
    "PluginCLIArgument",
    "PluginCLICommand",
    "PluginCLIContribution",
    "PluginComposerCommand",
    "PluginContext",
    "PluginRuntimeHandle",
    "PluginRuntimeManager",
    "PluginSidebarWidget",
    "PluginUIContribution",
    "PluginUIMode",
    "PluginUIView",
    "PluginWidgetAction",
    "PluginRegistry",
    "PluginResource",
    "PluginStateStore",
    "build_plugin_operation_catalog",
    "load_enabled_plugin_backends",
    "load_plugin_backend",
    "attach_plugin_runtime",
    "start_plugin_backend",
    "stop_plugin_backend",
    "shutdown_plugin_backends",
    "default_project_hooks_path",
    "default_project_plugin_root",
    "default_user_hooks_path",
    "default_user_plugin_root",
    # canonical hook event names
    "HOOK_EVENT_PRE_TOOL_USE",
    "HOOK_EVENT_POST_TOOL_USE",
    "HOOK_EVENT_POST_TOOL_USE_FAILURE",
    "HOOK_EVENT_SESSION_START",
    "HOOK_EVENT_SESSION_STOP",
    "HOOK_EVENT_USER_PROMPT_SUBMIT",
    "HOOK_EVENT_PERMISSION_REQUEST",
]
