//! Scope-separated Raw -> Resource -> Note vault.
//!
//! Raw evidence and versioned Resources live in SQLite.  A Note's editable
//! body lives in a UTF-8 Markdown file; SQLite only indexes identity, lineage,
//! locks and the last accepted body hash.  Frontmatter and the source footer
//! are always regenerated by the host.

use super::{identifier, search_snippet, search_text, StudyError, StudyResult, StudyStore};
use rusqlite::{params, Connection, OptionalExtension, Row, Transaction, TransactionBehavior};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{
    collections::{HashMap, HashSet},
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NoteWriter {
    User,
    Agent,
}

/// Stable id for an immutable host snapshot.  The content digest means an
/// edited source becomes a new Raw row while repeated sync is idempotent.
pub fn immutable_raw_id(kind: &str, origin_id: &str, content: &str) -> String {
    format!("{kind}-{origin_id}-{}", &hex_hash(content)[..16])
}

#[derive(Clone, Debug)]
struct Document {
    body: String,
    content_hash: String,
}

#[derive(Clone, Debug)]
struct NoteRow {
    id: String,
    title: String,
    revision: i64,
    source_json: String,
    path: String,
    parent_id: String,
    content_hash: String,
}

type NoteLinkIndex = HashMap<String, Vec<Value>>;

impl NoteRow {
    fn from_row(row: &Row<'_>) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get("id")?,
            title: row.get("title")?,
            revision: row.get("revision")?,
            source_json: row.get("source_json")?,
            path: row.get("path")?,
            parent_id: row.get("parent_id")?,
            content_hash: row.get("content_hash")?,
        })
    }
}

pub(super) fn ensure_schema(connection: &Connection) -> StudyResult<()> {
    connection.execute_batch(
        "CREATE TABLE IF NOT EXISTS study_notes(
           scope_key TEXT NOT NULL, id TEXT NOT NULL, title TEXT NOT NULL, revision INTEGER NOT NULL,
           source_json TEXT NOT NULL, deleted_at TEXT, path TEXT NOT NULL DEFAULT '',
           parent_id TEXT NOT NULL DEFAULT '', content_hash TEXT NOT NULL DEFAULT '',
           PRIMARY KEY(scope_key,id));
         CREATE TABLE IF NOT EXISTS study_note_resources(
           scope_key TEXT NOT NULL, id TEXT NOT NULL, note_id TEXT NOT NULL DEFAULT '',
           title TEXT NOT NULL, content TEXT NOT NULL, raw_refs_json TEXT NOT NULL,
           origin TEXT NOT NULL, revision INTEGER NOT NULL, deleted_at TEXT,
           created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           PRIMARY KEY(scope_key,id));
         CREATE INDEX IF NOT EXISTS study_note_resources_note
           ON study_note_resources(scope_key,note_id,created_at,id);
         CREATE TABLE IF NOT EXISTS study_note_resource_versions(
           scope_key TEXT NOT NULL, resource_id TEXT NOT NULL, revision INTEGER NOT NULL,
           title TEXT NOT NULL, content TEXT NOT NULL, raw_refs_json TEXT NOT NULL,
           origin TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           PRIMARY KEY(scope_key,resource_id,revision));
         CREATE TABLE IF NOT EXISTS study_note_raw_sources(
           scope_key TEXT NOT NULL, id TEXT NOT NULL, kind TEXT NOT NULL,
           origin_id TEXT NOT NULL, content TEXT NOT NULL, metadata_json TEXT NOT NULL,
           captured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           PRIMARY KEY(scope_key,id));
         CREATE INDEX IF NOT EXISTS study_note_raw_origin
           ON study_note_raw_sources(scope_key,kind,origin_id,captured_at,id);
         CREATE TABLE IF NOT EXISTS study_note_locks(
           scope_key TEXT NOT NULL, id TEXT NOT NULL, note_id TEXT NOT NULL,
           start_offset INTEGER NOT NULL, end_offset INTEGER NOT NULL,
           quote TEXT NOT NULL, prefix TEXT NOT NULL, suffix TEXT NOT NULL,
           reason TEXT NOT NULL, state TEXT NOT NULL, revision INTEGER NOT NULL,
           created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
           PRIMARY KEY(scope_key,id),
           FOREIGN KEY(scope_key,note_id) REFERENCES study_notes(scope_key,id) ON DELETE CASCADE);
         CREATE INDEX IF NOT EXISTS study_note_locks_note
           ON study_note_locks(scope_key,note_id,start_offset,end_offset);
         CREATE TABLE IF NOT EXISTS study_curation_tasks(
           scope_key TEXT NOT NULL, id TEXT NOT NULL, state TEXT NOT NULL,
           checkpoint_json TEXT NOT NULL, cancel_requested INTEGER NOT NULL DEFAULT 0,
           revision INTEGER NOT NULL DEFAULT 1, PRIMARY KEY(scope_key,id));",
    )?;
    // A database created by an older Python/Rust runtime can have the v2
    // notes table.  Upgrade it in place without touching legacy block rows.
    let mut statement = connection.prepare("PRAGMA table_info(study_notes)")?;
    let columns = statement
        .query_map([], |row| row.get::<_, String>(1))?
        .collect::<Result<HashSet<_>, _>>()?;
    for (name, declaration) in [
        ("path", "TEXT NOT NULL DEFAULT ''"),
        ("parent_id", "TEXT NOT NULL DEFAULT ''"),
        ("content_hash", "TEXT NOT NULL DEFAULT ''"),
    ] {
        if !columns.contains(name) {
            connection.execute(
                &format!("ALTER TABLE study_notes ADD COLUMN {name} {declaration}"),
                [],
            )?;
        }
    }
    connection.execute_batch(
        "CREATE UNIQUE INDEX IF NOT EXISTS study_note_path
           ON study_notes(scope_key,path) WHERE path<>'' AND deleted_at IS NULL;",
    )?;
    Ok(())
}

/// One-way compatibility migration for databases that still contain the old
/// SQLite NoteBlock body.  The old table remains readable for audit/recovery,
/// but every runtime operation uses the Markdown document after this marker.
pub(super) fn migrate_legacy(store: &StudyStore, db: &Connection) -> StudyResult<()> {
    let marker: bool = db.query_row(
        "SELECT EXISTS(SELECT 1 FROM study_scope_meta WHERE scope_key=?1 AND key='notes_v3_migrated')",
        [store.scope.key()],
        |row| row.get(0),
    )?;
    if marker {
        return Ok(());
    }
    let has_blocks: bool = db.query_row(
        "SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type='table' AND name='study_note_blocks')",
        [],
        |row| row.get(0),
    )?;
    let mut note_statement = db.prepare(
        "SELECT id,title,revision,source_json,path,parent_id,content_hash
         FROM study_notes WHERE scope_key=?1 AND deleted_at IS NULL AND path='' ORDER BY rowid",
    )?;
    let legacy_notes = note_statement
        .query_map([store.scope.key()], NoteRow::from_row)?
        .collect::<Result<Vec<_>, _>>()?;
    let mut existing = db
        .prepare(
            "SELECT path FROM study_notes WHERE scope_key=?1 AND deleted_at IS NULL AND path<>''",
        )?
        .query_map([store.scope.key()], |row| row.get::<_, String>(0))?
        .collect::<Result<HashSet<_>, _>>()?;
    for note in legacy_notes {
        let blocks = if has_blocks {
            let mut statement = db.prepare(
                "SELECT id,author,content,locked FROM study_note_blocks
                 WHERE scope_key=?1 AND note_id=?2 ORDER BY position,id",
            )?;
            let blocks = statement
                .query_map(params![store.scope.key(), note.id], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, String>(1)?,
                        row.get::<_, String>(2)?,
                        row.get::<_, bool>(3)?,
                    ))
                })?
                .collect::<Result<Vec<_>, _>>()?;
            blocks
        } else {
            Vec::new()
        };
        let body = blocks
            .iter()
            .map(|(_, _, content, _)| content.as_str())
            .collect::<Vec<_>>()
            .join("\n\n");
        let mut resources = Vec::new();
        let mut pending_locks = Vec::new();
        let mut offset = 0usize;
        for (block_id, author, content, locked) in &blocks {
            if !resources.is_empty() {
                offset += 2;
            }
            let start = offset;
            offset += content.chars().count();
            let raw_id = format!("legacy-raw-{}-{block_id}", note.id);
            let resource_id = format!("legacy-resource-{}-{block_id}", note.id);
            let metadata = json!({"note_id": note.id, "block_id": block_id, "author": author});
            db.execute(
                "INSERT OR IGNORE INTO study_note_raw_sources(scope_key,id,kind,origin_id,content,metadata_json)
                 VALUES(?1,?2,'legacy_note_block',?3,?4,?5)",
                params![store.scope.key(), raw_id, block_id, content, metadata.to_string()],
            )?;
            db.execute(
                "INSERT OR IGNORE INTO study_note_resources(scope_key,id,note_id,title,content,raw_refs_json,origin,revision,deleted_at)
                 VALUES(?1,?2,?3,?4,?5,?6,'legacy_migration',1,NULL)",
                params![store.scope.key(), resource_id, note.id, note.title, content, json!([raw_id]).to_string()],
            )?;
            db.execute(
                "INSERT OR IGNORE INTO study_note_resource_versions(scope_key,resource_id,revision,title,content,raw_refs_json,origin)
                 VALUES(?1,?2,1,?3,?4,?5,'legacy_migration')",
                params![store.scope.key(), resource_id, note.title, content, json!([raw_id]).to_string()],
            )?;
            resources.push(resource_id);
            if *locked || author == "user" {
                pending_locks.push((block_id.clone(), start, offset, content.clone()));
            }
        }
        if resources.is_empty() {
            let raw_id = format!("legacy-raw-note-{}", note.id);
            let resource_id = format!("legacy-resource-{}", note.id);
            db.execute(
                "INSERT OR IGNORE INTO study_note_raw_sources(scope_key,id,kind,origin_id,content,metadata_json)
                 VALUES(?1,?2,'legacy_empty_note',?3,'',?4)",
                params![store.scope.key(), raw_id, note.id, json!({"note_id":note.id,"empty_note":true}).to_string()],
            )?;
            db.execute(
                "INSERT OR IGNORE INTO study_note_resources(scope_key,id,note_id,title,content,raw_refs_json,origin,revision,deleted_at)
                 VALUES(?1,?2,?3,?4,'',?5,'legacy_migration',1,NULL)",
                params![store.scope.key(), resource_id, note.id, note.title, json!([raw_id]).to_string()],
            )?;
            db.execute(
                "INSERT OR IGNORE INTO study_note_resource_versions(scope_key,resource_id,revision,title,content,raw_refs_json,origin)
                 VALUES(?1,?2,1,?3,'',?4,'legacy_migration')",
                params![store.scope.key(), resource_id, note.title, json!([raw_id]).to_string()],
            )?;
            resources.push(resource_id);
        }
        let root = vault_root(store);
        let mut path = normalize_path(None, &note.title, &note.id, &existing)?;
        if fs::symlink_metadata(resolve_path(&root, &path)?).is_ok() {
            existing.insert(path);
            path = normalize_path(None, &note.title, &note.id, &existing)?;
        }
        existing.insert(path.clone());
        let metadata = note_metadata(
            &note.id,
            &note.title,
            "",
            &resources,
            note.revision,
            resource_refs(store, db, &resources)?,
        );
        let document = write_document_new(&root, &path, &metadata, &body)?;
        db.execute(
            "UPDATE study_notes SET path=?1,parent_id='',content_hash=?2,source_json=?3 WHERE scope_key=?4 AND id=?5",
            params![path, document.content_hash, json!({"resource_ids":resources}).to_string(), store.scope.key(), note.id],
        )?;
        for (block_id, start, end, quote) in pending_locks {
            db.execute(
                "INSERT OR IGNORE INTO study_note_locks(scope_key,id,note_id,start_offset,end_offset,quote,prefix,suffix,reason,state,revision)
                 VALUES(?1,?2,?3,?4,?5,?6,?7,?8,'Migrated protected content','active',1)",
                params![store.scope.key(), format!("legacy-lock-{}-{block_id}", note.id), note.id,
                    char_to_utf16(&body, start), char_to_utf16(&body, end), quote,
                    slice_chars(&body, start.saturating_sub(32), start),
                    slice_chars(&body, end, (end + 32).min(body.chars().count()))],
            )?;
        }
    }
    db.execute(
        "INSERT OR REPLACE INTO study_scope_meta(scope_key,key,data) VALUES(?1,'notes_v3_migrated','1')",
        [store.scope.key()],
    )?;
    Ok(())
}

impl StudyStore {
    /// Trusted host entry point.  Model-facing and ordinary RPC payloads can
    /// never supply Raw content directly.
    pub fn capture_note_raw(
        &self,
        raw_id: Option<&str>,
        kind: &str,
        origin_id: &str,
        content: &str,
        metadata: &Value,
    ) -> StudyResult<Value> {
        let kind = kind.trim();
        let origin_id = origin_id.trim();
        if kind.is_empty() || origin_id.is_empty() || !metadata.is_object() {
            return Err(StudyError::new(
                "Raw kind, origin_id and object metadata are required",
            ));
        }
        let connection = self.connect()?;
        let id = raw_id
            .filter(|value| !value.trim().is_empty())
            .map(str::to_owned)
            .unwrap_or_else(identifier);
        connection
            .execute(
                "INSERT INTO study_note_raw_sources(scope_key,id,kind,origin_id,content,metadata_json)
                 VALUES(?1,?2,?3,?4,?5,?6)",
                params![self.scope.key(), id, kind, origin_id, content, serde_json::to_string(metadata)?],
            )
            .map_err(|error| {
                if matches!(error, rusqlite::Error::SqliteFailure(ref code, _) if code.code == rusqlite::ErrorCode::ConstraintViolation) {
                    note_error("RAW_EXISTS", [("raw_id", json!(id))])
                } else {
                    error.into()
                }
            })?;
        Ok(json!({"raw_id": id, "immutable": true}))
    }

    /// Resolve a graph-owned Raw source without accepting caller-authored
    /// content.  Session messages are resolved by the native host because its
    /// session repository is outside the shared Study database.
    pub fn capture_note_record_raw(
        &self,
        raw_id: Option<&str>,
        kind: &str,
        origin_id: &str,
    ) -> StudyResult<Value> {
        if !matches!(kind, "mark" | "exam" | "node") {
            return Err(StudyError::new(
                "Raw kind must be session_message, mark, exam or node",
            ));
        }
        let connection = self.connect()?;
        let content: String = connection
            .query_row(
                "SELECT data FROM study_records WHERE scope_key=?1 AND kind=?2 AND id=?3",
                params![self.scope.key(), kind, origin_id],
                |row| row.get(0),
            )
            .optional()?
            .ok_or_else(|| StudyError::new("UNKNOWN_RAW_SOURCE"))?;
        self.capture_note_raw(
            raw_id,
            kind,
            origin_id,
            &content,
            &json!({"record_kind": kind}),
        )
    }

    /// Execute the public Study Note operation contract under a trusted writer
    /// identity supplied by the host/tool boundary.
    pub fn notes(&self, payload: &Value, writer: NoteWriter) -> StudyResult<Value> {
        let action = payload
            .get("action")
            .and_then(Value::as_str)
            .unwrap_or("list");
        let mut connection = self.connect()?;
        match action {
            "curate_start" | "curate_resume" | "curate_cancel" | "curate_checkpoint"
            | "task_create" | "task_checkpoint" | "task_cancel" | "task_resume" | "task_get" => {
                curation_task(self, &mut connection, payload, action)
            }
            "raw_capture" => Err(StudyError::new("RAW_CAPTURE_FORBIDDEN")),
            "raw_list" => {
                sync_record_raw_sources(self, &connection)?;
                raw_list(self, &connection, payload)
            }
            "raw_get" => raw_get(self, &connection, payload),
            "resource_list" => resource_list(self, &connection, payload),
            "resource_get" => resource_get(self, &connection, payload),
            "resource_create" | "resource_update" => {
                if writer != NoteWriter::Agent {
                    return Err(StudyError::new("RESOURCE_AGENT_ONLY"));
                }
                let transaction = connection.transaction()?;
                let result = write_resource(self, &transaction, payload, action)?;
                transaction.commit()?;
                Ok(result)
            }
            "list" | "tree" => list_notes(self, &connection, payload, action == "tree"),
            "get" => get_note(self, &connection, payload),
            "graph" | "backlinks" => note_graph(self, &connection, payload, action),
            "create" => {
                let transaction = connection.transaction()?;
                let result = create_note(self, &transaction, payload)?;
                transaction.commit()?;
                Ok(result)
            }
            "update" => {
                let transaction = connection.transaction()?;
                let result = update_note(self, &transaction, payload, writer)?;
                transaction.commit()?;
                Ok(result)
            }
            "lock_range" | "unlock_range" => {
                if writer != NoteWriter::User {
                    return Err(StudyError::new("NOTE_LOCK_FORBIDDEN"));
                }
                let transaction = connection.transaction()?;
                let result = mutate_lock(self, &transaction, payload, action)?;
                transaction.commit()?;
                Ok(result)
            }
            _ => Err(StudyError::new("Unknown note action")),
        }
    }
}

#[derive(Clone)]
struct CurationTask {
    id: String,
    state: String,
    checkpoint: Value,
    cancel_requested: bool,
    revision: i64,
}

fn curation_row(
    db: &Connection,
    scope: &str,
    id: Option<&str>,
    active_only: bool,
) -> StudyResult<Option<CurationTask>> {
    let sql = if let Some(_) = id {
        "SELECT id,state,checkpoint_json,cancel_requested,revision FROM study_curation_tasks WHERE scope_key=?1 AND id=?2"
    } else if active_only {
        "SELECT id,state,checkpoint_json,cancel_requested,revision FROM study_curation_tasks WHERE scope_key=?1 AND state IN ('pending','running') ORDER BY rowid DESC LIMIT 1"
    } else {
        "SELECT id,state,checkpoint_json,cancel_requested,revision FROM study_curation_tasks WHERE scope_key=?1 AND state IN ('pending','running','cancelled') ORDER BY rowid DESC LIMIT 1"
    };
    let read = |row: &Row<'_>| -> rusqlite::Result<(String, String, String, i64, i64)> {
        Ok((
            row.get(0)?,
            row.get(1)?,
            row.get(2)?,
            row.get(3)?,
            row.get(4)?,
        ))
    };
    let raw = if let Some(id) = id {
        db.query_row(sql, params![scope, id], read).optional()?
    } else {
        db.query_row(sql, [scope], read).optional()?
    };
    raw.map(|(id, state, checkpoint, cancel, revision)| {
        Ok(CurationTask {
            id,
            state,
            checkpoint: serde_json::from_str(&checkpoint)?,
            cancel_requested: cancel != 0,
            revision,
        })
    })
    .transpose()
}

fn curation_task(
    store: &StudyStore,
    db: &mut Connection,
    payload: &Value,
    action: &str,
) -> StudyResult<Value> {
    let scope = store.scope.key();
    if action == "task_get" {
        let id = payload.get("task_id").and_then(Value::as_str).unwrap_or("");
        let task = curation_row(db, &scope, Some(id), false)?
            .ok_or_else(|| StudyError::new("Unknown curation task"))?;
        return Ok(json!({
            "scope_key": scope, "id": task.id, "state": task.state,
            "checkpoint_json": serde_json::to_string(&task.checkpoint)?,
            "cancel_requested": task.cancel_requested, "revision": task.revision,
            "checkpoint": task.checkpoint,
        }));
    }
    let tx = db.transaction_with_behavior(TransactionBehavior::Immediate)?;
    if action == "curate_start" {
        if let Some(task) = curation_row(&tx, &scope, None, true)? {
            return Ok(json!({"task_id": task.id, "state": task.state,
                "checkpoint": task.checkpoint, "cancel_requested": task.cancel_requested,
                "revision": task.revision, "created": false}));
        }
    }
    if matches!(action, "curate_start" | "task_create") {
        let id = payload
            .get("task_id")
            .and_then(Value::as_str)
            .filter(|id| !id.is_empty())
            .map(str::to_owned)
            .unwrap_or_else(identifier);
        let checkpoint = if action == "curate_start" {
            payload
                .get("checkpoint")
                .filter(|value| value.is_object())
                .cloned()
                .unwrap_or_else(|| json!({}))
        } else {
            payload
                .get("checkpoint")
                .filter(|value| !value.is_null())
                .cloned()
                .unwrap_or_else(|| json!({}))
        };
        if !checkpoint.is_object() {
            return Err(StudyError::new("Curation checkpoint must be an object"));
        }
        let state = if action == "curate_start" {
            "running"
        } else {
            "pending"
        };
        tx.execute("INSERT INTO study_curation_tasks(scope_key,id,state,checkpoint_json,cancel_requested,revision) VALUES(?1,?2,?3,?4,0,1)",
            params![scope, id, state, serde_json::to_string(&checkpoint)?])?;
        tx.commit()?;
        return if action == "curate_start" {
            Ok(
                json!({"task_id": id, "state": state, "checkpoint": checkpoint,
                "cancel_requested": false, "revision": 1, "created": true}),
            )
        } else {
            Ok(json!({"task_id": id, "state": state, "revision": 1}))
        };
    }
    let explicit_id = payload
        .get("task_id")
        .and_then(Value::as_str)
        .filter(|id| !id.trim().is_empty());
    let task = curation_row(
        &tx,
        &scope,
        explicit_id.or(if action.starts_with("task_") {
            Some("")
        } else {
            None
        }),
        false,
    )?
    .ok_or_else(|| StudyError::new("Unknown curation task"))?;
    let expected = payload.get("expected_revision").and_then(Value::as_i64);
    if expected != Some(task.revision) && (action.starts_with("task_") || expected.is_some()) {
        return Err(StudyError::new("REVISION_CONFLICT"));
    }
    let (state, cancelled) = match action {
        "curate_cancel" | "task_cancel" => ("cancelled".to_owned(), true),
        "curate_resume" => ("running".to_owned(), false),
        "task_resume" => ("pending".to_owned(), false),
        _ => (
            payload
                .get("state")
                .and_then(Value::as_str)
                .unwrap_or("running")
                .to_owned(),
            task.cancel_requested,
        ),
    };
    if action == "curate_checkpoint"
        && !matches!(
            state.as_str(),
            "pending" | "running" | "completed" | "cancelled" | "failed"
        )
    {
        return Err(StudyError::new("Invalid curation task state"));
    }
    let checkpoint = payload
        .get("checkpoint")
        .cloned()
        .unwrap_or(task.checkpoint);
    if !checkpoint.is_object() {
        return Err(StudyError::new("Curation checkpoint must be an object"));
    }
    tx.execute("UPDATE study_curation_tasks SET state=?1,checkpoint_json=?2,cancel_requested=?3,revision=revision+1 WHERE scope_key=?4 AND id=?5",
        params![state, serde_json::to_string(&checkpoint)?, cancelled as i64, scope, task.id])?;
    tx.commit()?;
    Ok(
        json!({"task_id": task.id, "state": state, "checkpoint": checkpoint,
        "cancel_requested": cancelled, "revision": task.revision + 1}),
    )
}

fn raw_list(store: &StudyStore, db: &Connection, payload: &Value) -> StudyResult<Value> {
    let (offset, limit) = page(payload);
    let total: i64 = db.query_row(
        "SELECT COUNT(*) FROM study_note_raw_sources WHERE scope_key=?1",
        [store.scope.key()],
        |row| row.get(0),
    )?;
    let mut statement = db.prepare(
        "SELECT id,kind,origin_id,content,metadata_json,captured_at
         FROM study_note_raw_sources WHERE scope_key=?1
         ORDER BY captured_at DESC,id LIMIT ?2 OFFSET ?3",
    )?;
    let rows = statement
        .query_map(params![store.scope.key(), limit, offset], |row| {
            Ok(json!({
                "id": row.get::<_, String>(0)?, "kind": row.get::<_, String>(1)?,
                "origin_id": row.get::<_, String>(2)?, "content": row.get::<_, String>(3)?,
                "metadata_json": row.get::<_, String>(4)?, "captured_at": row.get::<_, String>(5)?,
            }))
        })?
        .collect::<Result<Vec<_>, _>>()?;
    let values = rows
        .into_iter()
        .map(decode_raw)
        .collect::<StudyResult<Vec<_>>>()?;
    Ok(
        json!({"raw_sources": values, "total": total, "offset": offset, "limit": limit, "has_more": offset + limit < total}),
    )
}

fn raw_get(store: &StudyStore, db: &Connection, payload: &Value) -> StudyResult<Value> {
    let id = string(payload, "raw_id");
    let row = db.query_row(
        "SELECT id,kind,origin_id,content,metadata_json,captured_at
         FROM study_note_raw_sources WHERE scope_key=?1 AND id=?2",
        params![store.scope.key(), id],
        |row| Ok(json!({
            "id": row.get::<_, String>(0)?, "kind": row.get::<_, String>(1)?,
            "origin_id": row.get::<_, String>(2)?, "content": row.get::<_, String>(3)?,
            "metadata_json": row.get::<_, String>(4)?, "captured_at": row.get::<_, String>(5)?,
        })),
    ).optional()?.ok_or_else(|| StudyError::new("UNKNOWN_RAW_SOURCE"))?;
    Ok(json!({"raw": decode_raw(row)?}))
}

fn decode_raw(mut value: Value) -> StudyResult<Value> {
    let object = value.as_object_mut().expect("raw projection is an object");
    let metadata_json = object
        .remove("metadata_json")
        .and_then(|value| value.as_str().map(str::to_owned))
        .unwrap_or_default();
    object.insert(
        "metadata".into(),
        serde_json::from_str(&metadata_json).unwrap_or_else(|_| json!({})),
    );
    object.insert("immutable".into(), Value::Bool(true));
    Ok(value)
}

fn sync_record_raw_sources(store: &StudyStore, db: &Connection) -> StudyResult<()> {
    let mut statement = db.prepare(
        "SELECT id,kind,data FROM study_records WHERE scope_key=?1 AND kind IN ('mark','exam','node') ORDER BY kind,id",
    )?;
    let rows = statement
        .query_map([store.scope.key()], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
            ))
        })?
        .collect::<Result<Vec<_>, _>>()?;
    for (origin_id, kind, content) in rows {
        let raw_id = immutable_raw_id(&kind, &origin_id, &content);
        db.execute(
            "INSERT OR IGNORE INTO study_note_raw_sources(scope_key,id,kind,origin_id,content,metadata_json)
             VALUES(?1,?2,?3,?4,?5,?6)",
            params![store.scope.key(), raw_id, kind, origin_id, content, json!({"record_kind": kind}).to_string()],
        )?;
    }
    Ok(())
}

fn resource_list(store: &StudyStore, db: &Connection, payload: &Value) -> StudyResult<Value> {
    let (offset, limit) = page(payload);
    let total: i64 = db.query_row(
        "SELECT COUNT(*) FROM study_note_resources WHERE scope_key=?1 AND deleted_at IS NULL",
        [store.scope.key()],
        |row| row.get(0),
    )?;
    let mut statement = db.prepare(
        "SELECT id,note_id,title,content,raw_refs_json,origin,revision,created_at,updated_at
         FROM study_note_resources WHERE scope_key=?1 AND deleted_at IS NULL
         ORDER BY updated_at DESC,id LIMIT ?2 OFFSET ?3",
    )?;
    let resources = statement
        .query_map(params![store.scope.key(), limit, offset], resource_value)?
        .collect::<Result<Vec<_>, _>>()?;
    Ok(
        json!({"resources": resources, "total": total, "offset": offset, "limit": limit, "has_more": offset + limit < total}),
    )
}

fn resource_get(store: &StudyStore, db: &Connection, payload: &Value) -> StudyResult<Value> {
    let id = string(payload, "resource_id");
    let requested = payload.get("revision").and_then(Value::as_i64);
    let resource = if let Some(revision) = requested {
        db.query_row(
            "SELECT resource_id AS id,'' AS note_id,title,content,raw_refs_json,origin,revision,created_at,created_at
             FROM study_note_resource_versions WHERE scope_key=?1 AND resource_id=?2 AND revision=?3",
            params![store.scope.key(), id, revision], resource_value).optional()?
    } else {
        db.query_row(
            "SELECT id,note_id,title,content,raw_refs_json,origin,revision,created_at,updated_at
             FROM study_note_resources WHERE scope_key=?1 AND id=?2 AND deleted_at IS NULL",
            params![store.scope.key(), id], resource_value).optional()?
    }.ok_or_else(|| StudyError::new("UNKNOWN_NOTE_RESOURCE"))?;
    let mut history_statement = db.prepare(
        "SELECT revision FROM study_note_resource_versions WHERE scope_key=?1 AND resource_id=?2 ORDER BY revision")?;
    let history = history_statement
        .query_map(params![store.scope.key(), id], |row| row.get::<_, i64>(0))?
        .collect::<Result<Vec<_>, _>>()?;
    let mut resource = resource;
    resource
        .as_object_mut()
        .unwrap()
        .insert("available_revisions".into(), json!(history));
    Ok(json!({"resource": resource}))
}

fn resource_value(row: &Row<'_>) -> rusqlite::Result<Value> {
    let raw: String = row.get(4)?;
    Ok(json!({
        "id": row.get::<_, String>(0)?, "note_id": row.get::<_, String>(1)?,
        "title": row.get::<_, String>(2)?, "content": row.get::<_, String>(3)?,
        "raw_refs_json": raw, "raw_ids": serde_json::from_str::<Value>(&row.get::<_, String>(4)?).unwrap_or_else(|_| json!([])),
        "origin": row.get::<_, String>(5)?, "revision": row.get::<_, i64>(6)?,
        "created_at": row.get::<_, String>(7)?, "updated_at": row.get::<_, String>(8)?,
    }))
}

fn write_resource(
    store: &StudyStore,
    db: &Transaction<'_>,
    payload: &Value,
    action: &str,
) -> StudyResult<Value> {
    let title = string(payload, "title").trim().to_owned();
    let content = string(payload, "content");
    if title.is_empty() || content.is_empty() {
        return Err(StudyError::new("Resource title and content are required"));
    }
    let raw_ids = unique_strings(payload.get("raw_ids"));
    if raw_ids.is_empty() {
        return Err(StudyError::new("RESOURCE_RAW_REQUIRED"));
    }
    validate_ids(
        db,
        "study_note_raw_sources",
        &store.scope.key(),
        &raw_ids,
        "UNKNOWN_RAW_SOURCE",
        "raw_ids",
    )?;
    let id = if action == "resource_create" {
        let supplied = string(payload, "resource_id");
        if supplied.trim().is_empty() {
            identifier()
        } else {
            supplied
        }
    } else {
        string(payload, "resource_id")
    };
    if action == "resource_create" {
        db.execute(
            "INSERT INTO study_note_resources(scope_key,id,note_id,title,content,raw_refs_json,origin,revision,deleted_at)
             VALUES(?1,?2,'',?3,?4,?5,'agent',1,NULL)",
            params![store.scope.key(), id, title, content, serde_json::to_string(&raw_ids)?],
        ).map_err(|error| constraint(error, "RESOURCE_EXISTS"))?;
        db.execute(
            "INSERT INTO study_note_resource_versions(scope_key,resource_id,revision,title,content,raw_refs_json,origin)
             VALUES(?1,?2,1,?3,?4,?5,'agent')",
            params![store.scope.key(), id, title, content, serde_json::to_string(&raw_ids)?],
        )?;
        return Ok(json!({"resource_id": id, "revision": 1}));
    }
    let current: i64 = db.query_row(
        "SELECT revision FROM study_note_resources WHERE scope_key=?1 AND id=?2 AND deleted_at IS NULL",
        params![store.scope.key(), id], |row| row.get(0)).optional()?
        .ok_or_else(|| StudyError::new("UNKNOWN_NOTE_RESOURCE"))?;
    if payload.get("expected_revision").and_then(Value::as_i64) != Some(current) {
        return Err(StudyError::new("REVISION_CONFLICT"));
    }
    let revision = current + 1;
    db.execute(
        "UPDATE study_note_resources SET title=?1,content=?2,raw_refs_json=?3,revision=?4,updated_at=CURRENT_TIMESTAMP
         WHERE scope_key=?5 AND id=?6",
        params![title, content, serde_json::to_string(&raw_ids)?, revision, store.scope.key(), id])?;
    db.execute(
        "INSERT INTO study_note_resource_versions(scope_key,resource_id,revision,title,content,raw_refs_json,origin)
         VALUES(?1,?2,?3,?4,?5,?6,'agent')",
        params![store.scope.key(), id, revision, title, content, serde_json::to_string(&raw_ids)?])?;
    Ok(json!({"resource_id": id, "revision": revision}))
}

fn list_notes(
    store: &StudyStore,
    db: &Connection,
    payload: &Value,
    tree: bool,
) -> StudyResult<Value> {
    let rows = note_rows(store, db)?;
    let query = payload
        .get("q")
        .or_else(|| payload.get("query"))
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_lowercase();
    let mut notes = Vec::new();
    for row in rows {
        let document = read_document(&vault_root(store), &row.path)?;
        if !query.is_empty()
            && !format!("{}\n{}", row.title, document.body)
                .to_lowercase()
                .contains(&query)
        {
            continue;
        }
        notes.push(note_summary(store, db, &row, &document)?);
    }
    if tree {
        let mut root = Vec::new();
        for note in &notes {
            let path = note.get("path").and_then(Value::as_str).unwrap_or("");
            insert_tree(&mut root, path, note.clone());
        }
        return Ok(json!({"tree": root, "notes": notes}));
    }
    let (offset, limit) = page(payload);
    let total = notes.len() as i64;
    let page_notes = notes
        .into_iter()
        .skip(offset as usize)
        .take(limit as usize)
        .collect::<Vec<_>>();
    Ok(
        json!({"notes": page_notes, "total": total, "offset": offset, "limit": limit, "has_more": offset + limit < total, "scope": store.scope.public()}),
    )
}

fn get_note(store: &StudyStore, db: &Connection, payload: &Value) -> StudyResult<Value> {
    let row = find_note(store, db, &string(payload, "note_id"))?;
    let document = read_document(&vault_root(store), &row.path)?;
    let (links, backlinks) = resolve_links(store, db)?;
    let mut statement = db.prepare(
        "SELECT id,start_offset,end_offset,quote,prefix,suffix,reason,state,revision,created_at,updated_at
         FROM study_note_locks WHERE scope_key=?1 AND note_id=?2 AND state IN ('active','orphaned') ORDER BY start_offset,id")?;
    let locks = statement.query_map(params![store.scope.key(), row.id], |lock| Ok(json!({
        "id": lock.get::<_, String>(0)?, "start_offset": lock.get::<_, i64>(1)?, "end_offset": lock.get::<_, i64>(2)?,
        "quote": lock.get::<_, String>(3)?, "prefix": lock.get::<_, String>(4)?, "suffix": lock.get::<_, String>(5)?,
        "reason": lock.get::<_, String>(6)?, "state": lock.get::<_, String>(7)?, "revision": lock.get::<_, i64>(8)?,
        "created_at": lock.get::<_, String>(9)?, "updated_at": lock.get::<_, String>(10)?, "unit": "utf16_code_unit",
    })))?.collect::<Result<Vec<_>, _>>()?;
    let mut note = note_summary(store, db, &row, &document)?;
    let object = note.as_object_mut().unwrap();
    object.insert("body_md".into(), json!(document.body));
    object.insert("locks".into(), json!(locks));
    object.insert(
        "links".into(),
        json!(links.get(&row.id).cloned().unwrap_or_default()),
    );
    object.insert(
        "backlinks".into(),
        json!(backlinks.get(&row.id).cloned().unwrap_or_default()),
    );
    Ok(json!({"note": note}))
}

fn create_note(store: &StudyStore, db: &Transaction<'_>, payload: &Value) -> StudyResult<Value> {
    let supplied = string(payload, "note_id");
    let id = if supplied.trim().is_empty() {
        identifier()
    } else {
        supplied
    };
    let title = string(payload, "title").trim().to_owned();
    if id.trim().is_empty() || title.is_empty() {
        return Err(StudyError::new("Note id and title are required"));
    }
    let exists: bool = db.query_row(
        "SELECT EXISTS(SELECT 1 FROM study_notes WHERE scope_key=?1 AND id=?2)",
        params![store.scope.key(), id],
        |row| row.get(0),
    )?;
    if exists {
        return Err(StudyError::new("NOTE_EXISTS"));
    }
    let resources = validate_resources(store, db, payload.get("resource_ids"))?;
    let parent = validate_parent(
        store,
        db,
        &id,
        payload
            .get("parent_id")
            .and_then(Value::as_str)
            .unwrap_or(""),
    )?;
    let existing = db
        .prepare(
            "SELECT path FROM study_notes WHERE scope_key=?1 AND deleted_at IS NULL AND path<>''",
        )?
        .query_map([store.scope.key()], |row| row.get::<_, String>(0))?
        .collect::<Result<HashSet<_>, _>>()?;
    let path = normalize_path(
        payload.get("path").and_then(Value::as_str),
        &title,
        &id,
        &existing,
    )?;
    if resolve_path(&vault_root(store), &path)?.exists() {
        return Err(StudyError::new("NOTE_PATH_EXISTS"));
    }
    let body = string(payload, "body_md");
    let metadata = note_metadata(
        &id,
        &title,
        &parent,
        &resources,
        1,
        resource_refs(store, db, &resources)?,
    );
    let document = write_document_new(&vault_root(store), &path, &metadata, &body)?;
    let result = db.execute(
        "INSERT INTO study_notes(scope_key,id,title,revision,source_json,deleted_at,path,parent_id,content_hash)
         VALUES(?1,?2,?3,1,?4,NULL,?5,?6,?7)",
        params![store.scope.key(), id, title, json!({"resource_ids": resources}).to_string(), path, parent, document.content_hash],
    );
    if let Err(error) = result {
        let _ = fs::remove_file(resolve_path(&vault_root(store), &path)?);
        return Err(constraint(error, "NOTE_PATH_EXISTS"));
    }
    Ok(json!({"note_id": id, "revision": 1, "content_hash": document.content_hash, "path": path}))
}

fn update_note(
    store: &StudyStore,
    db: &Transaction<'_>,
    payload: &Value,
    writer: NoteWriter,
) -> StudyResult<Value> {
    let id = string(payload, "note_id");
    let row = find_note(store, db, &id)?;
    let current = read_document(&vault_root(store), &row.path)?;
    if current.content_hash != row.content_hash && writer == NoteWriter::Agent {
        return Err(note_error(
            "NOTE_EXTERNAL_CHANGE",
            [("content_hash", json!(current.content_hash))],
        ));
    }
    if payload.get("expected_revision").and_then(Value::as_i64) != Some(row.revision) {
        return Err(StudyError::new("REVISION_CONFLICT"));
    }
    if payload.get("expected_content_hash").and_then(Value::as_str)
        != Some(current.content_hash.as_str())
    {
        return Err(note_error(
            "CONTENT_HASH_CONFLICT",
            [("content_hash", json!(current.content_hash))],
        ));
    }
    let body = string(payload, "body_md");
    let resources = validate_resources(store, db, payload.get("resource_ids"))?;
    let title = payload
        .get("title")
        .and_then(Value::as_str)
        .unwrap_or(&row.title)
        .trim()
        .to_owned();
    if title.is_empty() {
        return Err(StudyError::new("Note title is required"));
    }
    let parent_value = payload
        .get("parent_id")
        .and_then(Value::as_str)
        .unwrap_or(&row.parent_id);
    let parent = validate_parent(store, db, &id, parent_value)?;
    let locks = active_locks(store, db, &id)?;
    let changed = changed_interval(&current.body, &body);
    if writer == NoteWriter::Agent {
        let mut overlaps = Vec::new();
        for lock in &locks {
            let state = lock.get("state").and_then(Value::as_str).unwrap_or("");
            let start_units = lock["start_offset"].as_i64().unwrap_or(0) as usize;
            let end_units = lock["end_offset"].as_i64().unwrap_or(0) as usize;
            let start = utf16_to_char(&current.body, start_units)?;
            let end = utf16_to_char(&current.body, end_units)?;
            if state == "orphaned" || overlaps_interval(start, end, changed) {
                let mut item = lock.clone();
                let object = item.as_object_mut().unwrap();
                if let Some(lock_id) = object.remove("id") {
                    object.insert("lock_id".into(), lock_id);
                }
                object.insert("start".into(), json!(start_units));
                object.insert("end".into(), json!(end_units));
                object.insert(
                    "overlap_start".into(),
                    json!(if state == "orphaned" { 0 } else { start_units }),
                );
                object.insert(
                    "overlap_end".into(),
                    json!(if state == "orphaned" {
                        utf16_len(&current.body)
                    } else {
                        end_units
                    }),
                );
                overlaps.push(item);
            }
        }
        if !overlaps.is_empty() {
            return Err(note_error(
                "NOTE_REGION_LOCKED",
                [("overlaps", json!(overlaps))],
            ));
        }
    }
    let revision = row.revision + 1;
    let old_resources = resource_ids(&row.source_json);
    let old_metadata = note_metadata(
        &row.id,
        &row.title,
        &row.parent_id,
        &old_resources,
        row.revision,
        resource_refs(store, db, &old_resources)?,
    );
    let metadata = note_metadata(
        &id,
        &title,
        &parent,
        &resources,
        revision,
        resource_refs(store, db, &resources)?,
    );
    let document = write_document(&vault_root(store), &row.path, &metadata, &body)?;
    let db_result: StudyResult<()> = (|| {
        db.execute(
            "UPDATE study_notes SET title=?1,revision=?2,source_json=?3,parent_id=?4,content_hash=?5 WHERE scope_key=?6 AND id=?7",
            params![title, revision, json!({"resource_ids": resources}).to_string(), parent, document.content_hash, store.scope.key(), id])?;
        if writer == NoteWriter::User {
            reanchor_locks(store, db, &id, &body, &locks, changed)?;
        }
        Ok(())
    })();
    if let Err(error) = db_result {
        let _ = write_document(&vault_root(store), &row.path, &old_metadata, &current.body);
        return Err(error);
    }
    Ok(json!({"note_id": id, "revision": revision, "content_hash": document.content_hash}))
}

fn mutate_lock(
    store: &StudyStore,
    db: &Transaction<'_>,
    payload: &Value,
    action: &str,
) -> StudyResult<Value> {
    let note_id = string(payload, "note_id");
    let row = find_note(store, db, &note_id)?;
    if action == "unlock_range" {
        let lock_id = string(payload, "lock_id");
        let changed = db.execute(
            "UPDATE study_note_locks SET state='released',revision=revision+1,updated_at=CURRENT_TIMESTAMP
             WHERE scope_key=?1 AND note_id=?2 AND id=?3 AND state='active'",
            params![store.scope.key(), note_id, lock_id])?;
        if changed == 0 {
            return Err(StudyError::new("UNKNOWN_NOTE_LOCK"));
        }
        return Ok(json!({"note_id": note_id, "lock_id": lock_id, "unlocked": true}));
    }
    if payload
        .get("unit")
        .and_then(Value::as_str)
        .unwrap_or("utf16_code_unit")
        != "utf16_code_unit"
    {
        return Err(note_error(
            "INVALID_NOTE_RANGE",
            [("unit", json!("utf16_code_unit"))],
        ));
    }
    let start = payload.get("start").and_then(Value::as_i64).unwrap_or(-1);
    let end = payload.get("end").and_then(Value::as_i64).unwrap_or(-1);
    if start < 0 || end <= start {
        return Err(StudyError::new("INVALID_NOTE_RANGE"));
    }
    let document = read_document(&vault_root(store), &row.path)?;
    let start_char = utf16_to_char(&document.body, start as usize)?;
    let end_char = utf16_to_char(&document.body, end as usize)?;
    let quote = slice_chars(&document.body, start_char, end_char);
    if quote.is_empty() {
        return Err(StudyError::new("INVALID_NOTE_RANGE"));
    }
    let lock_id = {
        let value = string(payload, "lock_id");
        if value.is_empty() {
            identifier()
        } else {
            value
        }
    };
    let chars = document.body.chars().collect::<Vec<_>>();
    let prefix = chars[start_char.saturating_sub(32)..start_char]
        .iter()
        .collect::<String>();
    let suffix = chars[end_char..(end_char + 32).min(chars.len())]
        .iter()
        .collect::<String>();
    let reason = payload
        .get("reason")
        .and_then(Value::as_str)
        .unwrap_or("User locked");
    db.execute(
        "INSERT INTO study_note_locks(scope_key,id,note_id,start_offset,end_offset,quote,prefix,suffix,reason,state,revision)
         VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,'active',1)",
        params![store.scope.key(), lock_id, note_id, start, end, quote, prefix, suffix, reason])?;
    Ok(
        json!({"note_id": note_id, "lock_id": lock_id, "start": start, "end": end, "quote": quote, "unit": "utf16_code_unit"}),
    )
}

fn note_graph(
    store: &StudyStore,
    db: &Connection,
    payload: &Value,
    action: &str,
) -> StudyResult<Value> {
    let rows = note_rows(store, db)?;
    let (links, backlinks) = resolve_links(store, db)?;
    if action == "backlinks" {
        let id = string(payload, "note_id");
        return Ok(
            json!({"note_id": id, "backlinks": backlinks.get(&id).cloned().unwrap_or_default()}),
        );
    }
    let nodes = rows
        .iter()
        .map(|row| json!({"id": row.id, "title": row.title, "path": row.path}))
        .collect::<Vec<_>>();
    let mut edges = Vec::new();
    for row in &rows {
        if !row.parent_id.is_empty() {
            edges.push(json!({"source": row.parent_id, "target": row.id, "kind": "parent"}));
        }
        for link in links.get(&row.id).into_iter().flatten() {
            if link.get("kind").and_then(Value::as_str) == Some("note") {
                edges.push(json!({"source": row.id, "target": link["id"], "kind": "wikilink"}));
            }
        }
    }
    Ok(json!({"nodes": nodes, "edges": edges}))
}

fn resolve_links(
    store: &StudyStore,
    db: &Connection,
) -> StudyResult<(NoteLinkIndex, NoteLinkIndex)> {
    let rows = note_rows(store, db)?;
    let by_id = rows
        .iter()
        .map(|row| (row.id.clone(), row))
        .collect::<HashMap<_, _>>();
    let mut by_title: HashMap<String, Vec<&NoteRow>> = HashMap::new();
    for row in &rows {
        by_title
            .entry(row.title.to_lowercase())
            .or_default()
            .push(row);
    }
    let mut links = HashMap::new();
    let mut backlinks: HashMap<String, Vec<Value>> = rows
        .iter()
        .map(|row| (row.id.clone(), Vec::new()))
        .collect();
    for row in &rows {
        let document = read_document(&vault_root(store), &row.path)?;
        let mut resolved = Vec::new();
        for (raw_target, label) in wikilinks(&document.body) {
            let target = raw_target
                .strip_prefix("note:")
                .unwrap_or(&raw_target)
                .trim();
            let candidate = by_id.get(target).copied().or_else(|| {
                let candidates = by_title.get(&target.to_lowercase())?;
                (candidates.len() == 1).then_some(candidates[0])
            });
            if let Some(target_row) = candidate {
                let item = json!({"target": raw_target, "label": label, "kind": "note", "id": target_row.id, "title": target_row.title});
                backlinks.entry(target_row.id.clone()).or_default().push(json!({"note_id": row.id, "title": row.title, "target": raw_target, "label": label}));
                resolved.push(item);
            } else {
                resolved.push(json!({"target": raw_target, "label": label, "kind": "unresolved"}));
            }
        }
        links.insert(row.id.clone(), resolved);
    }
    Ok((links, backlinks))
}

fn note_rows(store: &StudyStore, db: &Connection) -> StudyResult<Vec<NoteRow>> {
    let mut statement = db.prepare(
        "SELECT id,title,revision,source_json,path,parent_id,content_hash
         FROM study_notes WHERE scope_key=?1 AND deleted_at IS NULL ORDER BY path,id",
    )?;
    let rows = statement
        .query_map([store.scope.key()], NoteRow::from_row)?
        .collect::<Result<Vec<_>, _>>()?;
    Ok(rows)
}

pub(super) fn search_notes(
    store: &StudyStore,
    db: &Connection,
    query: &str,
) -> StudyResult<Vec<Value>> {
    let folded = query.to_lowercase();
    let mut results = Vec::new();
    let mut rows = note_rows(store, db)?;
    rows.sort_by(|a, b| a.id.cmp(&b.id));
    for row in rows {
        let source: Value = serde_json::from_str(&row.source_json)?;
        let body = read_document(&vault_root(store), &row.path)?.body;
        let searchable = format!("{} {} {}", row.title, search_text(Some(&source)), body);
        if searchable.to_lowercase().contains(&folded) {
            results.push(json!({
                "entity_type": "note", "kind": "note",
                "entity_id": row.id, "note_id": row.id,
                "title": row.title,
                "snippet": search_snippet(&searchable, query, 240),
                "target": {"kind": "note", "id": row.id},
            }));
        }
    }
    Ok(results)
}

fn find_note(store: &StudyStore, db: &Connection, id: &str) -> StudyResult<NoteRow> {
    db.query_row(
        "SELECT id,title,revision,source_json,path,parent_id,content_hash
         FROM study_notes WHERE scope_key=?1 AND id=?2 AND deleted_at IS NULL",
        params![store.scope.key(), id],
        NoteRow::from_row,
    )
    .optional()?
    .ok_or_else(|| StudyError::new("UNKNOWN_NOTE"))
}

fn note_summary(
    store: &StudyStore,
    db: &Connection,
    row: &NoteRow,
    document: &Document,
) -> StudyResult<Value> {
    let ids = resource_ids(&row.source_json);
    Ok(json!({
        "id": row.id, "title": row.title, "revision": row.revision, "source_json": row.source_json,
        "deleted_at": Value::Null, "path": row.path, "parent_id": row.parent_id,
        "content_hash": document.content_hash, "indexed_content_hash": row.content_hash,
        "external_change": document.content_hash != row.content_hash,
        "resource_ids": ids, "resources": note_resources(store, db, &ids)?,
    }))
}

fn note_resources(store: &StudyStore, db: &Connection, ids: &[String]) -> StudyResult<Vec<Value>> {
    if ids.is_empty() {
        return Ok(Vec::new());
    }
    let placeholders = std::iter::repeat_n("?", ids.len())
        .collect::<Vec<_>>()
        .join(",");
    let sql = format!("SELECT id,title,origin,revision,raw_refs_json,created_at,updated_at FROM study_note_resources WHERE scope_key=? AND deleted_at IS NULL AND id IN ({placeholders})");
    let scope_key = store.scope.key();
    let mut values: Vec<&dyn rusqlite::ToSql> = vec![&scope_key];
    for id in ids {
        values.push(id);
    }
    let mut statement = db.prepare(&sql)?;
    let rows = statement.query_map(values.as_slice(), |row| Ok(json!({
        "id": row.get::<_, String>(0)?, "title": row.get::<_, String>(1)?, "origin": row.get::<_, String>(2)?,
        "revision": row.get::<_, i64>(3)?, "raw_ids": serde_json::from_str::<Value>(&row.get::<_, String>(4)?).unwrap_or_else(|_| json!([])),
        "created_at": row.get::<_, String>(5)?, "updated_at": row.get::<_, String>(6)?,
    })))?.collect::<Result<Vec<_>, _>>()?;
    let by_id = rows
        .into_iter()
        .map(|row| (row["id"].as_str().unwrap_or("").to_owned(), row))
        .collect::<HashMap<_, _>>();
    Ok(ids.iter().filter_map(|id| by_id.get(id).cloned()).collect())
}

fn active_locks(store: &StudyStore, db: &Connection, note_id: &str) -> StudyResult<Vec<Value>> {
    let mut statement = db.prepare(
        "SELECT id,start_offset,end_offset,quote,prefix,suffix,reason,state,revision
         FROM study_note_locks WHERE scope_key=?1 AND note_id=?2 AND state IN ('active','orphaned')")?;
    let rows = statement.query_map(params![store.scope.key(), note_id], |row| Ok(json!({
        "id": row.get::<_, String>(0)?, "start_offset": row.get::<_, i64>(1)?, "end_offset": row.get::<_, i64>(2)?,
        "quote": row.get::<_, String>(3)?, "prefix": row.get::<_, String>(4)?, "suffix": row.get::<_, String>(5)?,
        "reason": row.get::<_, String>(6)?, "state": row.get::<_, String>(7)?, "revision": row.get::<_, i64>(8)?,
    })))?.collect::<Result<Vec<_>, _>>()?;
    Ok(rows)
}

fn reanchor_locks(
    store: &StudyStore,
    db: &Connection,
    _note_id: &str,
    body: &str,
    locks: &[Value],
    changed: (usize, usize),
) -> StudyResult<()> {
    for lock in locks {
        let id = lock["id"].as_str().unwrap_or("");
        let quote = lock["quote"].as_str().unwrap_or("");
        let occurrences = char_occurrences(body, quote);
        let old_start = utf16_to_char(
            body,
            lock["start_offset"].as_i64().unwrap_or(0).max(0) as usize,
        )
        .unwrap_or(0);
        let candidate = if occurrences.len() == 1 {
            Some(occurrences[0])
        } else {
            None
        };
        let (start, end, state) = if let Some(start) = candidate {
            (start, start + quote.chars().count(), "active")
        } else if !overlaps_interval(old_start, old_start + quote.chars().count(), changed)
            && old_start + quote.chars().count() <= body.chars().count()
        {
            (old_start, old_start + quote.chars().count(), "active")
        } else {
            (0, 0, "orphaned")
        };
        let chars = body.chars().collect::<Vec<_>>();
        let current_quote = chars[start..end].iter().collect::<String>();
        let prefix = chars[start.saturating_sub(32)..start]
            .iter()
            .collect::<String>();
        let suffix = chars[end..(end + 32).min(chars.len())]
            .iter()
            .collect::<String>();
        db.execute(
            "UPDATE study_note_locks SET start_offset=?1,end_offset=?2,quote=?3,prefix=?4,suffix=?5,state=?6,revision=revision+1,updated_at=CURRENT_TIMESTAMP
             WHERE scope_key=?7 AND id=?8",
            params![char_to_utf16(body, start), char_to_utf16(body, end), current_quote, prefix, suffix, state, store.scope.key(), id])?;
    }
    Ok(())
}

fn validate_resources(
    store: &StudyStore,
    db: &Connection,
    value: Option<&Value>,
) -> StudyResult<Vec<String>> {
    let ids = unique_strings(value);
    if ids.is_empty() {
        return Err(StudyError::new("NOTE_RESOURCES_REQUIRED"));
    }
    validate_ids(
        db,
        "study_note_resources",
        &store.scope.key(),
        &ids,
        "UNKNOWN_NOTE_RESOURCE",
        "resource_ids",
    )?;
    Ok(ids)
}

fn validate_ids(
    db: &Connection,
    table: &str,
    scope: &str,
    ids: &[String],
    error: &str,
    detail: &str,
) -> StudyResult<()> {
    let placeholders = std::iter::repeat_n("?", ids.len())
        .collect::<Vec<_>>()
        .join(",");
    let deleted = if table == "study_note_resources" {
        " AND deleted_at IS NULL"
    } else {
        ""
    };
    let sql =
        format!("SELECT id FROM {table} WHERE scope_key=? AND id IN ({placeholders}){deleted}");
    let mut values: Vec<&dyn rusqlite::ToSql> = vec![&scope];
    for id in ids {
        values.push(id);
    }
    let mut statement = db.prepare(&sql)?;
    let found = statement
        .query_map(values.as_slice(), |row| row.get::<_, String>(0))?
        .collect::<Result<HashSet<_>, _>>()?;
    let missing = ids
        .iter()
        .filter(|id| !found.contains(*id))
        .cloned()
        .collect::<Vec<_>>();
    if missing.is_empty() {
        Ok(())
    } else {
        Err(note_error(error, [(detail, json!(missing))]))
    }
}

fn validate_parent(
    store: &StudyStore,
    db: &Connection,
    note_id: &str,
    parent: &str,
) -> StudyResult<String> {
    let parent = parent.trim();
    if parent.is_empty() {
        return Ok(String::new());
    }
    if parent == note_id {
        return Err(StudyError::new("NOTE_PARENT_CYCLE"));
    }
    let mut current = parent.to_owned();
    let mut seen = HashSet::from([note_id.to_owned()]);
    while !current.is_empty() {
        if !seen.insert(current.clone()) {
            return Err(StudyError::new("NOTE_PARENT_CYCLE"));
        }
        current = db.query_row(
            "SELECT parent_id FROM study_notes WHERE scope_key=?1 AND id=?2 AND deleted_at IS NULL",
            params![store.scope.key(), current], |row| row.get::<_, String>(0)).optional()?
            .ok_or_else(|| StudyError::new("UNKNOWN_PARENT_NOTE"))?;
    }
    Ok(parent.to_owned())
}

fn resource_refs(store: &StudyStore, db: &Connection, ids: &[String]) -> StudyResult<Vec<Value>> {
    let resources = note_resources(store, db, ids)?;
    Ok(resources
        .into_iter()
        .map(|item| json!({"id": item["id"], "title": item["title"]}))
        .collect())
}

fn resource_ids(source_json: &str) -> Vec<String> {
    unique_strings(
        serde_json::from_str::<Value>(source_json)
            .ok()
            .as_ref()
            .and_then(|value| value.get("resource_ids")),
    )
}

fn note_metadata(
    id: &str,
    title: &str,
    parent: &str,
    resources: &[String],
    revision: i64,
    refs: Vec<Value>,
) -> Value {
    json!({"id": id, "title": title, "parent_id": if parent.is_empty() { Value::Null } else { json!(parent) }, "resource_ids": resources, "resource_refs": refs, "revision": revision})
}

fn vault_root(store: &StudyStore) -> PathBuf {
    let digest = hex_hash(&store.scope.key());
    store
        .path
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("study-notes")
        .join(&digest[..24])
}

fn write_document(
    root: &Path,
    relative: &str,
    metadata: &Value,
    body: &str,
) -> StudyResult<Document> {
    write_document_with_policy(root, relative, metadata, body, true)
}

fn write_document_new(
    root: &Path,
    relative: &str,
    metadata: &Value,
    body: &str,
) -> StudyResult<Document> {
    write_document_with_policy(root, relative, metadata, body, false)
}

fn write_document_with_policy(
    root: &Path,
    relative: &str,
    metadata: &Value,
    body: &str,
    replace: bool,
) -> StudyResult<Document> {
    let target = resolve_path(root, relative)?;
    let canonical_root = checked_vault_root(root, true)?;
    let parent = target
        .parent()
        .ok_or_else(|| StudyError::new("INVALID_NOTE_PATH"))?;
    fs::create_dir_all(parent)?;
    if !fs::canonicalize(parent)?.starts_with(&canonical_root)
        || fs::symlink_metadata(&target).is_ok_and(|metadata| metadata.file_type().is_symlink())
    {
        return Err(StudyError::new("INVALID_NOTE_PATH"));
    }
    let temporary = target.with_file_name(format!(
        ".{}.{}.tmp",
        target
            .file_name()
            .and_then(|v| v.to_str())
            .unwrap_or("note"),
        identifier()
    ));
    let serialized = serialize_document(metadata, body);
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)?;
    file.write_all(serialized.as_bytes())?;
    file.sync_all()?;
    drop(file);
    let write_result = if replace {
        atomic_replace(&temporary, &target)
    } else {
        atomic_create(&temporary, &target)
    };
    if let Err(error) = write_result {
        // `rename` is the platform atomic replacement primitive.  Never
        // delete the destination as a fallback: if replacement is refused,
        // preserve the previously committed Note and discard only the temp.
        return Err(if error.kind() == std::io::ErrorKind::AlreadyExists {
            StudyError::new("NOTE_PATH_EXISTS")
        } else {
            error.into()
        });
    }
    let body = body.trim_end_matches('\n').to_owned();
    Ok(Document {
        content_hash: hex_hash(&body),
        body,
    })
}

fn atomic_replace(temporary: &Path, target: &Path) -> std::io::Result<()> {
    if let Err(error) = fs::rename(temporary, target) {
        let _ = fs::remove_file(temporary);
        return Err(error);
    }
    Ok(())
}

fn atomic_create(temporary: &Path, target: &Path) -> std::io::Result<()> {
    let result = fs::hard_link(temporary, target);
    let _ = fs::remove_file(temporary);
    result
}

fn checked_vault_root(root: &Path, create: bool) -> StudyResult<PathBuf> {
    let container = root
        .parent()
        .ok_or_else(|| StudyError::new("INVALID_NOTE_PATH"))?;
    let database_dir = container
        .parent()
        .ok_or_else(|| StudyError::new("INVALID_NOTE_PATH"))?;
    let reject_symlink = |path: &Path| {
        if fs::symlink_metadata(path).is_ok_and(|entry| entry.file_type().is_symlink()) {
            Err(StudyError::new("INVALID_NOTE_PATH"))
        } else {
            Ok(())
        }
    };
    if create {
        fs::create_dir_all(database_dir)?;
        reject_symlink(container)?;
        fs::create_dir_all(container)?;
        reject_symlink(root)?;
        fs::create_dir_all(root)?;
    }
    reject_symlink(container)?;
    reject_symlink(root)?;
    let canonical_root = match fs::canonicalize(root) {
        Ok(value) => value,
        Err(error) if !create && error.kind() == std::io::ErrorKind::NotFound => {
            return Err(StudyError::new("NOTE_FILE_MISSING"));
        }
        Err(error) => return Err(error.into()),
    };
    let expected = fs::canonicalize(database_dir)?
        .join(
            container
                .file_name()
                .ok_or_else(|| StudyError::new("INVALID_NOTE_PATH"))?,
        )
        .join(
            root.file_name()
                .ok_or_else(|| StudyError::new("INVALID_NOTE_PATH"))?,
        );
    if canonical_root != expected {
        return Err(StudyError::new("INVALID_NOTE_PATH"));
    }
    Ok(canonical_root)
}

fn read_document(root: &Path, relative: &str) -> StudyResult<Document> {
    let target = resolve_path(root, relative)?;
    let canonical_root = checked_vault_root(root, false)?;
    let canonical_target = fs::canonicalize(&target).map_err(|error| {
        if error.kind() == std::io::ErrorKind::NotFound {
            StudyError::new("NOTE_FILE_MISSING")
        } else {
            error.into()
        }
    })?;
    if !canonical_target.starts_with(canonical_root) {
        return Err(StudyError::new("INVALID_NOTE_PATH"));
    }
    let raw = fs::read_to_string(canonical_target).map_err(|error| match error.kind() {
        std::io::ErrorKind::NotFound => StudyError::new("NOTE_FILE_MISSING"),
        std::io::ErrorKind::InvalidData => StudyError::new("NOTE_FILE_NOT_UTF8"),
        _ => error.into(),
    })?;
    let mut content = raw.as_str();
    if content.starts_with("---\n") {
        if let Some(end) = content[4..].find("\n---\n") {
            content = &content[4 + end + 5..];
        }
    }
    if let Some(start) = content.rfind("\n<!-- lamtools:sources-begin -->\n") {
        content = &content[..start];
    }
    let body = content.trim_end_matches('\n').to_owned();
    Ok(Document {
        content_hash: hex_hash(&body),
        body,
    })
}

fn serialize_document(metadata: &Value, body: &str) -> String {
    let mut lines = vec!["---".to_owned()];
    for key in ["id", "title", "parent_id", "resource_ids", "revision"] {
        lines.push(format!(
            "{key}: {}",
            serde_json::to_string(&metadata[key]).unwrap_or_else(|_| "null".into())
        ));
    }
    lines.push("---".into());
    lines.push(body.trim_end_matches('\n').to_owned());
    lines.push(String::new());
    lines.push("<!-- lamtools:sources-begin -->".into());
    let refs = metadata
        .get("resource_refs")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let rendered = refs
        .iter()
        .filter_map(|item| {
            let id = item.get("id")?.as_str()?;
            let title = markdown_label(item.get("title").and_then(Value::as_str).unwrap_or(id));
            Some(format!(
                "[{title}](lamtools-resource://{})",
                percent_encode(id)
            ))
        })
        .collect::<Vec<_>>()
        .join(" · ");
    lines.push(format!("> 来源：{rendered}"));
    lines.push(format!(
        "<!-- lamtools:sources {} -->",
        serde_json::to_string(&metadata["resource_ids"]).unwrap_or_else(|_| "[]".into())
    ));
    lines.join("\n")
}

fn resolve_path(root: &Path, relative: &str) -> StudyResult<PathBuf> {
    let normalized = relative.replace('\\', "/");
    if normalized.is_empty()
        || normalized.starts_with('/')
        || !normalized.to_lowercase().ends_with(".md")
        || normalized
            .split('/')
            .any(|part| part.is_empty() || part == "." || part == "..")
    {
        return Err(StudyError::new("INVALID_NOTE_PATH"));
    }
    let mut target = root.to_path_buf();
    for part in normalized.split('/') {
        target.push(part);
    }
    Ok(target)
}

fn normalize_path(
    requested: Option<&str>,
    title: &str,
    id: &str,
    existing: &HashSet<String>,
) -> StudyResult<String> {
    let raw = requested.unwrap_or("").replace('\\', "/").trim().to_owned();
    let mut parts = if raw.is_empty() {
        vec![safe_segment(title, "note")]
    } else {
        if raw.starts_with('/')
            || raw
                .split('/')
                .any(|part| part.is_empty() || part == "." || part == "..")
        {
            return Err(StudyError::new("INVALID_NOTE_PATH"));
        }
        raw.split('/')
            .enumerate()
            .map(|(index, part)| safe_segment(part, &format!("folder-{}", index + 1)))
            .collect()
    };
    let last = parts.last_mut().unwrap();
    if !last.to_lowercase().ends_with(".md") {
        last.push_str(".md");
    }
    let path = parts.join("/");
    let folded = existing
        .iter()
        .map(|item| item.to_lowercase())
        .collect::<HashSet<_>>();
    if !folded.contains(&path.to_lowercase()) {
        return Ok(path);
    }
    let (stem, _) = path.rsplit_once('.').unwrap_or((&path, "md"));
    let candidate = format!("{}-{}.md", stem, &hex_hash(id)[..8]);
    if folded.contains(&candidate.to_lowercase()) {
        Err(StudyError::new("NOTE_PATH_EXISTS"))
    } else {
        Ok(candidate)
    }
}

fn safe_segment(value: &str, fallback: &str) -> String {
    let invalid = "<>:\"/\\|?*";
    let mut result = value
        .trim()
        .chars()
        .map(|character| {
            if invalid.contains(character) || (character as u32) < 32 {
                '-'
            } else {
                character
            }
        })
        .collect::<String>();
    result = result.split_whitespace().collect::<Vec<_>>().join(" ");
    result = result
        .trim_matches(&[' ', '.', '-'][..])
        .chars()
        .take(96)
        .collect();
    let reserved = matches!(
        result.to_lowercase().as_str(),
        "con"
            | "prn"
            | "aux"
            | "nul"
            | "com1"
            | "com2"
            | "com3"
            | "com4"
            | "com5"
            | "com6"
            | "com7"
            | "com8"
            | "com9"
            | "lpt1"
            | "lpt2"
            | "lpt3"
            | "lpt4"
            | "lpt5"
            | "lpt6"
            | "lpt7"
            | "lpt8"
            | "lpt9"
    );
    if result.is_empty() || reserved {
        fallback.to_owned()
    } else {
        result
    }
}

fn insert_tree(root: &mut Vec<Value>, path: &str, note: Value) {
    let parts = path.split('/').collect::<Vec<_>>();
    let mut children = root;
    let mut accumulated = Vec::new();
    for segment in &parts[..parts.len().saturating_sub(1)] {
        accumulated.push(*segment);
        let folder_path = accumulated.join("/");
        let index = children.iter().position(|item| {
            item.get("kind").and_then(Value::as_str) == Some("folder")
                && item.get("path").and_then(Value::as_str) == Some(folder_path.as_str())
        });
        let index = index.unwrap_or_else(|| {
            children.push(json!({"kind":"folder", "id": format!("folder:{}", folder_path.to_lowercase()), "name": segment, "path": folder_path, "children": []}));
            children.len() - 1
        });
        children = children[index]
            .get_mut("children")
            .and_then(Value::as_array_mut)
            .unwrap();
    }
    let mut leaf = note;
    let object = leaf.as_object_mut().unwrap();
    object.insert("kind".into(), json!("note"));
    object.insert(
        "note_id".into(),
        object.get("id").cloned().unwrap_or(Value::Null),
    );
    children.push(leaf);
}

fn wikilinks(body: &str) -> Vec<(String, String)> {
    let mut links = Vec::new();
    let mut fenced = false;
    for line in body.lines() {
        if line.trim_start().starts_with("```") {
            fenced = !fenced;
            continue;
        }
        if fenced {
            continue;
        }
        let mut inline = false;
        let chars = line.chars().collect::<Vec<_>>();
        let mut index = 0;
        while index + 1 < chars.len() {
            if chars[index] == '`' {
                inline = !inline;
                index += 1;
                continue;
            }
            if !inline && chars[index] == '[' && chars[index + 1] == '[' {
                if let Some(end) = (index + 2..chars.len().saturating_sub(1))
                    .find(|&value| chars[value] == ']' && chars[value + 1] == ']')
                {
                    let inner = chars[index + 2..end].iter().collect::<String>();
                    let (target, label) = inner
                        .split_once('|')
                        .map(|(a, b)| (a.trim(), b.trim()))
                        .unwrap_or((inner.trim(), inner.trim()));
                    if !target.is_empty() {
                        links.push((target.to_owned(), label.to_owned()));
                    }
                    index = end + 2;
                    continue;
                }
            }
            index += 1;
        }
    }
    links
}

fn changed_interval(old: &str, new: &str) -> (usize, usize) {
    let old_chars = old.chars().collect::<Vec<_>>();
    let new_chars = new.chars().collect::<Vec<_>>();
    let prefix = old_chars
        .iter()
        .zip(&new_chars)
        .take_while(|(a, b)| a == b)
        .count();
    let suffix = old_chars[prefix..]
        .iter()
        .rev()
        .zip(new_chars[prefix..].iter().rev())
        .take_while(|(a, b)| a == b)
        .count();
    (prefix, old_chars.len().saturating_sub(suffix))
}

fn overlaps_interval(start: usize, end: usize, changed: (usize, usize)) -> bool {
    let (changed_start, changed_end) = changed;
    if changed_start == changed_end {
        start < changed_start && changed_start < end
    } else {
        start.max(changed_start) < end.min(changed_end)
    }
}

fn utf16_len(value: &str) -> usize {
    value.encode_utf16().count()
}
fn char_to_utf16(value: &str, offset: usize) -> usize {
    value.chars().take(offset).map(char::len_utf16).sum()
}
fn utf16_to_char(value: &str, offset: usize) -> StudyResult<usize> {
    let mut units = 0;
    for (index, character) in value.chars().enumerate() {
        if units == offset {
            return Ok(index);
        }
        units += character.len_utf16();
        if units > offset {
            return Err(StudyError::new("INVALID_NOTE_RANGE"));
        }
    }
    if units == offset {
        Ok(value.chars().count())
    } else {
        Err(StudyError::new("INVALID_NOTE_RANGE"))
    }
}

fn slice_chars(value: &str, start: usize, end: usize) -> String {
    value
        .chars()
        .skip(start)
        .take(end.saturating_sub(start))
        .collect()
}
fn char_occurrences(value: &str, needle: &str) -> Vec<usize> {
    if needle.is_empty() {
        return Vec::new();
    }
    let mut result = Vec::new();
    let chars = value.chars().collect::<Vec<_>>();
    let needle = needle.chars().collect::<Vec<_>>();
    for index in 0..=chars.len().saturating_sub(needle.len()) {
        if chars[index..index + needle.len()] == needle {
            result.push(index);
        }
    }
    result
}

fn page(payload: &Value) -> (i64, i64) {
    (
        payload
            .get("offset")
            .and_then(Value::as_i64)
            .unwrap_or(0)
            .max(0),
        payload
            .get("limit")
            .and_then(Value::as_i64)
            .unwrap_or(20)
            .clamp(1, 50),
    )
}
fn string(payload: &Value, key: &str) -> String {
    payload
        .get(key)
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_owned()
}
fn unique_strings(value: Option<&Value>) -> Vec<String> {
    let mut seen = HashSet::new();
    value
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .filter(|value| seen.insert((*value).to_owned()))
        .map(str::to_owned)
        .collect()
}
fn hex_hash(value: &str) -> String {
    format!("{:x}", Sha256::digest(value.as_bytes()))
}
fn markdown_label(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('\\', "\\\\")
        .replace('[', "\\[")
        .replace(']', "\\]")
}
fn percent_encode(value: &str) -> String {
    value
        .as_bytes()
        .iter()
        .map(|byte| {
            if byte.is_ascii_alphanumeric() || b"-._~".contains(byte) {
                (*byte as char).to_string()
            } else {
                format!("%{byte:02X}")
            }
        })
        .collect()
}
fn constraint(error: rusqlite::Error, code: &str) -> StudyError {
    if matches!(error, rusqlite::Error::SqliteFailure(ref detail, _) if detail.code == rusqlite::ErrorCode::ConstraintViolation)
    {
        StudyError::new(code)
    } else {
        error.into()
    }
}
fn note_error<const N: usize>(message: &str, details: [(&str, Value); N]) -> StudyError {
    let mut error = StudyError::new(message);
    error.details.extend(
        details
            .into_iter()
            .map(|(key, value)| (key.to_owned(), value)),
    );
    error
}

#[cfg(test)]
mod tests {
    use super::super::StudyScope;
    use super::*;
    use serde_json::Map;

    fn store(name: &str, scope: StudyScope) -> (PathBuf, StudyStore) {
        let root = std::env::temp_dir().join(format!(
            "sunday-study-notes-{name}-{}-{}",
            std::process::id(),
            identifier()
        ));
        let store = StudyStore::open(root.join("study.db"), scope).unwrap();
        (root, store)
    }

    fn seed(store: &StudyStore) -> (String, String) {
        let raw = store
            .capture_note_raw(
                Some("raw-1"),
                "node",
                "node-1",
                "真实快照",
                &json!({"kind":"node"}),
            )
            .unwrap();
        let raw_id = raw["raw_id"].as_str().unwrap().to_owned();
        let resource = store.notes(&json!({"action":"resource_create", "resource_id":"res-1", "title":"素材", "content":"归纳", "raw_ids":[raw_id]}), NoteWriter::Agent).unwrap();
        (raw_id, resource["resource_id"].as_str().unwrap().to_owned())
    }

    #[test]
    fn raw_resource_note_round_trip_preserves_host_owned_envelope() {
        let (root, store) = store("round-trip", StudyScope::local_compatibility());
        let (_, resource_id) = seed(&store);
        let created = store.notes(&json!({"action":"create", "note_id":"note-1", "title":"极限", "path":"数学/极限.md", "body_md":"# 极限\n\n正文", "resource_ids":[resource_id]}), NoteWriter::Agent).unwrap();
        assert_eq!(created["revision"], 1);
        let read = store
            .notes(
                &json!({"action":"get", "note_id":"note-1"}),
                NoteWriter::User,
            )
            .unwrap();
        assert_eq!(read["note"]["body_md"], "# 极限\n\n正文");
        let file = fs::read_to_string(vault_root(&store).join("数学/极限.md")).unwrap();
        assert!(file.contains("lamtools:sources-begin"));
        assert!(file.contains("lamtools-resource://res-1"));
        assert!(!read["note"]["body_md"]
            .as_str()
            .unwrap()
            .contains("lamtools:sources"));
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn cas_versions_scope_and_agent_locks_are_enforced() {
        let scope = StudyScope::new("user-a", "phone", "library");
        let (root, store) = store("cas-lock", scope.clone());
        let (_, resource_id) = seed(&store);
        let created = store.notes(&json!({"action":"create", "note_id":"note-1", "title":"N", "body_md":"A😀LOCKZ", "resource_ids":[resource_id]}), NoteWriter::Agent).unwrap();
        store.notes(&json!({"action":"lock_range", "note_id":"note-1", "start":3, "end":7, "unit":"utf16_code_unit", "reason":"保留"}), NoteWriter::User).unwrap();
        let locked = store.notes(&json!({"action":"update", "note_id":"note-1", "title":"N", "body_md":"A😀EDITZ", "resource_ids":["res-1"], "expected_revision":1, "expected_content_hash":created["content_hash"]}), NoteWriter::Agent).unwrap_err();
        assert_eq!(locked.message(), "NOTE_REGION_LOCKED");
        assert_eq!(locked.payload()["overlaps"][0]["reason"], "保留");
        let updated = store.notes(&json!({"action":"update", "note_id":"note-1", "title":"N", "body_md":"!A😀LOCKZ", "resource_ids":["res-1"], "expected_revision":1, "expected_content_hash":created["content_hash"]}), NoteWriter::Agent).unwrap();
        assert_eq!(updated["revision"], 2);
        let conflict = store.notes(&json!({"action":"update", "note_id":"note-1", "body_md":"stale", "resource_ids":["res-1"], "expected_revision":1, "expected_content_hash":created["content_hash"]}), NoteWriter::User).unwrap_err();
        assert_eq!(conflict.message(), "REVISION_CONFLICT");
        let other = store.scoped(StudyScope::new("user-b", "phone", "library"));
        assert!(other
            .notes(
                &json!({"action":"get", "note_id":"note-1"}),
                NoteWriter::User
            )
            .is_err());
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn resource_history_search_tree_graph_and_pins_are_real() {
        let (root, store) = store("surfaces", StudyScope::local_compatibility());
        seed(&store);
        store.notes(&json!({"action":"resource_update", "resource_id":"res-1", "title":"素材 v2", "content":"第二版", "raw_ids":["raw-1"], "expected_revision":1}), NoteWriter::Agent).unwrap();
        let old = store
            .notes(
                &json!({"action":"resource_get", "resource_id":"res-1", "revision":1}),
                NoteWriter::Agent,
            )
            .unwrap();
        assert_eq!(old["resource"]["content"], "归纳");
        store.notes(&json!({"action":"create", "note_id":"a", "title":"Alpha", "path":"课/Alpha.md", "body_md":"needle [[Beta]]", "resource_ids":["res-1"]}), NoteWriter::Agent).unwrap();
        store.notes(&json!({"action":"create", "note_id":"b", "title":"Beta", "path":"课/Beta.md", "body_md":"target", "resource_ids":["res-1"], "parent_id":"a"}), NoteWriter::Agent).unwrap();
        assert_eq!(
            store
                .notes(&json!({"action":"list", "q":"needle"}), NoteWriter::User)
                .unwrap()["total"],
            1
        );
        assert_eq!(
            store
                .notes(&json!({"action":"tree"}), NoteWriter::User)
                .unwrap()["tree"][0]["kind"],
            "folder"
        );
        assert_eq!(
            store
                .notes(&json!({"action":"graph"}), NoteWriter::User)
                .unwrap()["edges"]
                .as_array()
                .unwrap()
                .len(),
            2
        );
        let pins = store
            .pins(
                &json!({"action":"add", "entity_type":"note", "entity_id":"a"}),
                &Map::new(),
            )
            .unwrap();
        assert_eq!(pins["pins"][0]["title"], "Alpha");
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn legacy_blocks_migrate_once_into_resources_markdown_and_locks() {
        let root = std::env::temp_dir().join(format!(
            "sunday-study-notes-legacy-{}-{}",
            std::process::id(),
            identifier()
        ));
        fs::create_dir_all(&root).unwrap();
        let path = root.join("study.db");
        let scope = StudyScope::local_compatibility();
        let db = Connection::open(&path).unwrap();
        db.execute_batch(
            "CREATE TABLE study_scope_meta(scope_key TEXT NOT NULL,key TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(scope_key,key));
             CREATE TABLE study_notes(scope_key TEXT NOT NULL,id TEXT NOT NULL,title TEXT NOT NULL,revision INTEGER NOT NULL,source_json TEXT NOT NULL,deleted_at TEXT,PRIMARY KEY(scope_key,id));
             CREATE TABLE study_note_blocks(scope_key TEXT NOT NULL,note_id TEXT NOT NULL,id TEXT NOT NULL,position INTEGER NOT NULL,author TEXT NOT NULL,content TEXT NOT NULL,locked INTEGER NOT NULL,revision INTEGER NOT NULL,source_json TEXT NOT NULL,PRIMARY KEY(scope_key,note_id,id));",
        ).unwrap();
        db.execute(
            "INSERT INTO study_notes VALUES(?1,'legacy-note','Legacy',3,'{}',NULL)",
            [scope.key()],
        )
        .unwrap();
        db.execute(
            "INSERT INTO study_note_blocks VALUES(?1,'legacy-note','block-1',0,'user','protected',1,1,'{}')",
            [scope.key()],
        )
        .unwrap();
        drop(db);

        let store = StudyStore::open(&path, scope).unwrap();
        let note = store
            .notes(
                &json!({"action":"get", "note_id":"legacy-note"}),
                NoteWriter::User,
            )
            .unwrap();
        assert_eq!(note["note"]["body_md"], "protected");
        assert_eq!(note["note"]["revision"], 3);
        assert_eq!(note["note"]["resource_ids"].as_array().unwrap().len(), 1);
        assert_eq!(note["note"]["locks"][0]["quote"], "protected");
        let reopened = StudyStore::open(&path, StudyScope::local_compatibility()).unwrap();
        assert_eq!(
            reopened
                .notes(&json!({"action":"resource_list"}), NoteWriter::User)
                .unwrap()["total"],
            1
        );
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn failed_atomic_replace_preserves_the_committed_document() {
        let root = std::env::temp_dir().join(format!(
            "sunday-study-notes-replace-{}-{}",
            std::process::id(),
            identifier()
        ));
        fs::create_dir_all(&root).unwrap();
        let target = root.join("note.md");
        fs::write(&target, "committed").unwrap();
        let missing_temporary = root.join("missing.tmp");
        assert!(atomic_replace(&missing_temporary, &target).is_err());
        assert_eq!(fs::read_to_string(&target).unwrap(), "committed");
        fs::remove_dir_all(root).unwrap();
    }
}
