"""LamTools Core application module — FastAPI app factory."""

from .agent_app import (
    AgentApp,
    AgentSpec,
    ModelProvider,
    ModelTurnInput,
    ModelTurnOutput,
    TurnInput,
    TurnResult,
)
from .factory import create_app
from .operation_catalog import OperationCatalog, OperationRequest, OperationResult, normalize_operation_name
from .operation_groups import CORE_WORKBENCH_OPERATION_NAMES, build_member_operation_catalog, register_operation_handlers
from .queue_state import (
    ACTIVE_TURN_STATUSES,
    QUEUE_TERMINAL_STATUSES,
    QueueGuidancePlan,
    build_queue_guidance_plan,
    effective_thread_status,
    effective_turn_status,
    input_item_attachment_ids,
    input_items_text,
    latest_active_turn_id,
    next_dispatchable_queue_item,
    queue_delete_payload,
    queue_dispatch_payload,
    queue_item_payload,
)
from .base_agent import (
    CoreBaseAgentConfig,
    CoreBaseAgentKit,
    assemble_core_agent_plugins,
    build_core_plugin_operation_catalog,
    core_events_to_run_items,
    core_events_to_snapshot,
    default_core_agent_plugin_roots,
)
from .default_agent import CoreAgentPaths, CoreAgentSpec, create_core_agent_operations
from .approval_continuation import CoreApprovalContinuationCoordinator, build_core_approval_operation
from .event_store import AppEventEnvelope, AppEventInput, CORE_RUN_ITEM_METHOD, SqlAlchemyAppEventStore
from .persistence_host import AppPersistenceHost
from .live_hub import CoreAppEventHub
from .live_member import (
    CoreLiveMemberHooks,
    DefaultCoreLiveMemberHooks,
    PreparedLiveInput,
    QueueMaterialization,
    TurnMaterialization,
)
from .live_client import CoreAppServerClient, app_server_event, app_server_event_dedupe_key
from .cli_live import CliLiveFormatter, CliLiveWatchResult, OutputChunk, watch_live_events
from .live_operations import (
    CoreLiveContext,
    CoreLiveOperationHost,
    CoreLiveOperationOutcome,
    handle_approval_respond_operation,
    handle_queue_guidance_operation,
    handle_thread_read_operation,
    handle_thread_resume_operation,
    handle_thread_start_operation,
    handle_turn_cancel_operation,
    handle_turn_start_operation,
    handle_turn_steer_operation,
)
from .live_router import CoreLiveConnection, CoreLiveConnectionAdapter
from .live_protocol import (
    PROTOCOL_VERSION as CORE_APP_SERVER_PROTOCOL_VERSION,
    JsonRpcRequest,
    event_notification,
    rpc_error,
    rpc_result,
    snapshot_notification,
)
from .snapshot_store import CoreAppSnapshotProjector, SqlAlchemyThreadSnapshotStore
from .core_db import CoreAppDb, CoreProject, open_core_app_db
from .project_store import CoreProjectRecord, CoreProjectStore
from .turn_acceptance import (
    CoreAppEventSpec,
    TURN_ACCEPT_DEDUPE_METHODS,
    TurnAcceptancePlan,
    build_cancelled_turn_event,
    build_turn_acceptance_plan,
)

__all__ = [
    "AgentApp",
    "AgentSpec",
    "AppEventEnvelope",
    "AppEventInput",
    "AppPersistenceHost",
    "ACTIVE_TURN_STATUSES",
    "QUEUE_TERMINAL_STATUSES",
    "QueueGuidancePlan",
    "CORE_RUN_ITEM_METHOD",
    "CoreAgentPaths",
    "CoreBaseAgentConfig",
    "CoreBaseAgentKit",
    "CoreAgentSpec",
    "CoreAppEventHub",
    "CoreAppEventSpec",
    "CoreAppDb",
    "CoreAppServerClient",
    "CoreApprovalContinuationCoordinator",
    "CliLiveFormatter",
    "CliLiveWatchResult",
    "OutputChunk",
    "CoreAppSnapshotProjector",
    "CoreLiveContext",
    "CoreLiveOperationHost",
    "CoreLiveConnection",
    "CoreLiveConnectionAdapter",
    "CoreLiveOperationOutcome",
    "CoreProject",
    "CoreProjectRecord",
    "CoreProjectStore",
    "CoreLiveMemberHooks",
    "DefaultCoreLiveMemberHooks",
    "PreparedLiveInput",
    "QueueMaterialization",
    "TurnMaterialization",
    "CORE_APP_SERVER_PROTOCOL_VERSION",
    "CORE_WORKBENCH_OPERATION_NAMES",
    "JsonRpcRequest",
    "ModelProvider",
    "ModelTurnInput",
    "ModelTurnOutput",
    "OperationCatalog",
    "OperationRequest",
    "OperationResult",
    "SqlAlchemyAppEventStore",
    "SqlAlchemyThreadSnapshotStore",
    "TURN_ACCEPT_DEDUPE_METHODS",
    "TurnAcceptancePlan",
    "TurnInput",
    "TurnResult",
    "assemble_core_agent_plugins",
    "app_server_event",
    "app_server_event_dedupe_key",
    "watch_live_events",
    "build_core_plugin_operation_catalog",
    "build_cancelled_turn_event",
    "build_queue_guidance_plan",
    "build_turn_acceptance_plan",
    "build_member_operation_catalog",
    "build_core_approval_operation",
    "create_app",
    "create_core_agent_operations",
    "core_events_to_run_items",
    "core_events_to_snapshot",
    "default_core_agent_plugin_roots",
    "event_notification",
    "effective_thread_status",
    "effective_turn_status",
    "handle_thread_read_operation",
    "handle_approval_respond_operation",
    "handle_queue_guidance_operation",
    "handle_thread_resume_operation",
    "handle_thread_start_operation",
    "handle_turn_cancel_operation",
    "handle_turn_start_operation",
    "handle_turn_steer_operation",
    "input_item_attachment_ids",
    "input_items_text",
    "latest_active_turn_id",
    "next_dispatchable_queue_item",
    "normalize_operation_name",
    "open_core_app_db",
    "queue_delete_payload",
    "queue_dispatch_payload",
    "queue_item_payload",
    "register_operation_handlers",
    "rpc_error",
    "rpc_result",
    "snapshot_notification",
]
