"""Original compact bilingual learning lexicon; no copied dictionary definitions.

These entries are intentionally concise. Unknown words use the lightweight
translation endpoint; no guessed lemma is treated as a dictionary hit.
"""

ENTRIES = {
    'a': ('/ə/', 'art.', '一个；某个', 'Introduces one unspecified thing.', ''),
    'the': ('/ðə/', 'art.', '这个；那个', 'Points to a particular thing already identifiable.', ''),
    'be': ('/biː/', 'v.', '是；存在', 'Have an identity, state, or existence.', ''),
    'have': ('/hæv/', 'v.', '有；拥有', 'Possess something or experience a state.', ''),
    'do': ('/duː/', 'v.', '做', 'Perform an action or task.', ''),
    'go': ('/ɡəʊ/', 'v.', '去；前往', 'Move toward a place.', ''),
    'come': ('/kʌm/', 'v.', '来', 'Move toward the speaker or a chosen place.', ''),
    'make': ('/meɪk/', 'v.', '制作；使得', 'Create something or bring about a result.', ''),
    'take': ('/teɪk/', 'v.', '拿；采取', 'Get hold of something or choose an action.', ''),
    'give': ('/ɡɪv/', 'v.', '给予', 'Let someone receive something.', ''),
    'get': ('/ɡet/', 'v.', '得到；变得', 'Receive something or enter a new state.', ''),
    'see': ('/siː/', 'v.', '看见；明白', 'Notice with the eyes or understand an idea.', ''),
    'know': ('/nəʊ/', 'v.', '知道', 'Have information or understanding.', ''),
    'think': ('/θɪŋk/', 'v.', '思考；认为', 'Use the mind to form ideas or judgments.', ''),
    'read': ('/riːd/', 'v.', '阅读', 'Understand information expressed in writing.', ''),
    'write': ('/raɪt/', 'v.', '写', 'Express ideas using written symbols.', ''),
    'speak': ('/spiːk/', 'v.', '说；讲话', 'Express words with the voice.', ''),
    'listen': ('/ˈlɪsən/', 'v.', '听', 'Pay attention to sound.', ''),
    'understand': ('/ˌʌndəˈstænd/', 'v.', '理解', 'Grasp what something means or how it works.', ''),
    'explain': ('/ɪkˈspleɪn/', 'v.', '解释', 'Make an idea easier to understand.', ''),
    'ask': ('/ɑːsk/', 'v.', '询问；请求', 'Say a question or make a request.', ''),
    'answer': ('/ˈɑːnsə/', 'n. / v.', '答案；回答', 'A response to a question; to provide that response.', ''),
    'question': ('/ˈkwestʃən/', 'n.', '问题', 'Words used to ask for information.', ''),
    'example': ('/ɪɡˈzɑːmpəl/', 'n.', '例子', 'A particular case that helps explain a general idea.', ''),
    'practice': ('/ˈpræktɪs/', 'n. / v.', '练习；实践', 'Repeated use of a skill to improve it.', ''),
    'test': ('/test/', 'n. / v.', '测试；检验', 'An activity used to check knowledge or behavior.', ''),
    'exam': ('/ɪɡˈzæm/', 'n.', '考试', 'An organized assessment of learning.', ''),
    'result': ('/rɪˈzʌlt/', 'n.', '结果', 'What follows from an action or process.', ''),
    'correct': ('/kəˈrekt/', 'adj. / v.', '正确的；纠正', 'Free from error; to remove an error.', ''),
    'error': ('/ˈerə/', 'n.', '错误', 'A difference from what is correct or intended.', ''),
    'reason': ('/ˈriːzən/', 'n.', '原因；理由', 'An explanation for why something happens or is believed.', ''),
    'evidence': ('/ˈevɪdəns/', 'n.', '证据', 'Information that supports or challenges a claim.', ''),
    'course': ('/kɔːs/', 'n.', '课程', 'An organized series of lessons on a subject.', ''),
    'lesson': ('/ˈlesən/', 'n.', '课；经验', 'A period of teaching or something learned from experience.', ''),
    'subject': ('/ˈsʌbdʒɪkt/', 'n.', '学科；主题', 'An area or topic being studied.', ''),
    'topic': ('/ˈtɒpɪk/', 'n.', '话题；主题', 'The particular matter being discussed.', ''),
    'book': ('/bʊk/', 'n.', '书', 'A collection of written pages or its digital equivalent.', ''),
    'word': ('/wɜːd/', 'n.', '单词；词', 'A unit of language carrying meaning.', ''),
    'sentence': ('/ˈsentəns/', 'n.', '句子', 'A grammatical group of words expressing a thought.', ''),
    'meaning': ('/ˈmiːnɪŋ/', 'n.', '含义', 'The idea communicated by words or signs.', ''),
    'language': ('/ˈlæŋɡwɪdʒ/', 'n.', '语言', 'A shared system for expressing and understanding ideas.', ''),
    'translate': ('/trænzˈleɪt/', 'v.', '翻译', 'Express the meaning of text in another language.', ''),
    'grammar': ('/ˈɡræmə/', 'n.', '语法', 'The patterns used to combine words in a language.', ''),
    'noun': ('/naʊn/', 'n.', '名词', 'A word that names a person, thing, place, or idea.', ''),
    'verb': ('/vɜːb/', 'n.', '动词', 'A word expressing an action or state.', ''),
    'adjective': ('/ˈædʒɪktɪv/', 'n.', '形容词', 'A word describing a noun.', ''),
    'number': ('/ˈnʌmbə/', 'n.', '数；数字', 'A value used to count, measure, or label.', ''),
    'sum': ('/sʌm/', 'n.', '和；总数', 'The value obtained by adding quantities.', ''),
    'difference': ('/ˈdɪfrəns/', 'n.', '差；差异', 'A subtraction result or a way things are unlike.', ''),
    'product': ('/ˈprɒdʌkt/', 'n.', '积；产品', 'A multiplication result or something produced.', ''),
    'fraction': ('/ˈfrækʃən/', 'n.', '分数；部分', 'A quantity written as one number divided by another.', ''),
    'equation': ('/ɪˈkweɪʒən/', 'n.', '方程；等式', 'A statement that two expressions have equal value.', ''),
    'variable': ('/ˈveəriəbəl/', 'n.', '变量', 'A symbol or storage location whose value may change.', ''),
    'constant': ('/ˈkɒnstənt/', 'n. / adj.', '常量；不变的', 'A value kept fixed in a given context.', ''),
    'formula': ('/ˈfɔːmjələ/', 'n.', '公式', 'A symbolic rule connecting quantities.', ''),
    'proof': ('/pruːf/', 'n.', '证明', 'A logical argument establishing a statement.', ''),
    'concept': ('/ˈkɒnsept/', 'n.', '概念', 'An idea used to recognize or reason about something.', ''),
    'method': ('/ˈmeθəd/', 'n.', '方法', 'An organized way to accomplish a task.', ''),
    'vector': ('/ˈvektə/', 'n.', '向量', 'An element of a vector space, often represented by ordered components.', ''),
    'matrix': ('/ˈmeɪtrɪks/', 'n.', '矩阵', 'Numbers or expressions arranged in rows and columns.', ''),
    'gradient': ('/ˈɡreɪdiənt/', 'n.', '梯度', 'The vector of first partial derivatives of a scalar function.', ''),
    'derivative': ('/dɪˈrɪvətɪv/', 'n.', '导数', 'The instantaneous rate at which a function changes.', ''),
    'integral': ('/ˈɪntɪɡrəl/', 'n.', '积分', 'A mathematical accumulation of continuously varying quantities.', ''),
    'limit': ('/ˈlɪmɪt/', 'n.', '极限；限制', 'A value approached by a sequence or function; a boundary.', ''),
    'probability': ('/ˌprɒbəˈbɪləti/', 'n.', '概率', 'A numerical measure of how likely an event is.', ''),
    'random': ('/ˈrændəm/', 'adj.', '随机的', 'Governed by chance rather than a fixed predictable choice.', ''),
    'sample': ('/ˈsɑːmpəl/', 'n.', '样本', 'A selected part used to study a larger group.', ''),
    'mean': ('/miːn/', 'n. / v.', '均值；意指', 'An average value; to express a meaning.', ''),
    'variance': ('/ˈveəriəns/', 'n.', '方差', 'The average squared distance from the mean.', ''),
    'algorithm': ('/ˈælɡərɪðəm/', 'n.', '算法', 'A defined sequence of steps for solving a problem.', ''),
    'structure': ('/ˈstrʌktʃə/', 'n.', '结构', 'The arrangement of parts and their connections.', ''),
    'array': ('/əˈreɪ/', 'n.', '数组', 'A collection whose elements are accessed by index.', ''),
    'list': ('/lɪst/', 'n.', '列表', 'A sequence of items.', ''),
    'tree': ('/triː/', 'n.', '树', 'A branching plant; a connected graph without cycles.', ''),
    'graph': ('/ɡrɑːf/', 'n.', '图；图表', 'Vertices connected by edges; a visual display of values.', ''),
    'node': ('/nəʊd/', 'n.', '节点', 'An individual point or item in a connected structure.', ''),
    'edge': ('/edʒ/', 'n.', '边；连接', 'A boundary or a connection between graph vertices.', ''),
    'network': ('/ˈnetwɜːk/', 'n.', '网络', 'A set of connected elements.', ''),
    'search': ('/sɜːtʃ/', 'v. / n.', '搜索', 'Look through information to find something.', ''),
    'sort': ('/sɔːt/', 'v.', '排序；分类', 'Arrange items according to an order or category.', ''),
    'stack': ('/stæk/', 'n.', '栈', 'A collection where the latest added item is removed first.', ''),
    'queue': ('/kjuː/', 'n.', '队列', 'A collection where the earliest added item is removed first.', ''),
    'memory': ('/ˈmeməri/', 'n.', '记忆；内存', 'The ability or storage used to retain information.', ''),
    'time': ('/taɪm/', 'n.', '时间', 'A measure of when events happen and how long they last.', ''),
    'space': ('/speɪs/', 'n.', '空间', 'Available room, or storage required by a computation.', ''),
    'input': ('/ˈɪnpʊt/', 'n.', '输入', 'Information supplied to a process.', ''),
    'output': ('/ˈaʊtpʊt/', 'n.', '输出', 'Information or a result produced by a process.', ''),
    'value': ('/ˈvæljuː/', 'n.', '值；价值', 'The quantity or content represented by something.', ''),
    'object': ('/ˈɒbdʒɪkt/', 'n.', '对象；物体', 'An identifiable thing; a programming unit with state and behavior.', ''),
    'class': ('/klɑːs/', 'n.', '类；班级', 'A category, a group of learners, or a definition for program objects.', ''),
    'recursion': ('/rɪˈkɜːʒən/', 'n.', '递归', 'Solving a problem by applying the same procedure to smaller instances.', ''),
    'iteration': ('/ˌɪtəˈreɪʃən/', 'n.', '迭代', 'One repetition of a procedure.', ''),
    'complexity': ('/kəmˈpleksəti/', 'n.', '复杂度', 'How resource requirements grow as a problem becomes larger.', ''),
    'science': ('/ˈsaɪəns/', 'n.', '科学', 'Systematic study using evidence and testable explanations.', ''),
    'theory': ('/ˈθɪəri/', 'n.', '理论', 'A connected set of ideas explaining a subject or phenomenon.', ''),
    'hypothesis': ('/haɪˈpɒθəsɪs/', 'n.', '假设', 'A proposed explanation that can be investigated.', ''),
    'experiment': ('/ɪkˈsperɪmənt/', 'n.', '实验', 'A planned observation used to test an idea.', ''),
    'energy': ('/ˈenədʒi/', 'n.', '能量', 'A conserved physical quantity associated with work and change.', ''),
    'force': ('/fɔːs/', 'n.', '力', 'An interaction that can change motion.', ''),
    'mass': ('/mæs/', 'n.', '质量', 'A physical quantity measuring inertia.', ''),
}
